// nodeDefs.js — Upgrade Tree upgrade definitions.
// Centralized node data for the upgrade tree.

// Tree Layout Constants
const TREE_CENTER_X = 400; // Half of 800px panel width
const TREE_START_Y = 740;
const TREE_UNIT_X = 80;
const TREE_UNIT_Y = 80;
const DUO_OFFSET = 30; // Standard offset for choice nodes

// Theme Colors for Popups/Effects
const COLORS = {
    COMBAT: '#' + GAME_CONSTANTS.COLOR_HOSTILE.toString(16).padStart(6, '0'),
    UTILITY: '#' + GAME_CONSTANTS.COLOR_FRIENDLY.toString(16).padStart(6, '0'),
    RESOURCE: '#' + GAME_CONSTANTS.COLOR_RESOURCE.toString(16).padStart(6, '0'),
    HEALTH: '#87FF02',
    LORE: '#a2a2a2',
    COIN: '#00FF00'
};

// Grid Helpers
const gridX = (units) => TREE_CENTER_X + TREE_UNIT_X * units;
const gridY = (units) => TREE_START_Y - TREE_UNIT_Y * units;

const NODE_DEFS = [
    {
        id: 'awaken',
        name: 'AWAKEN',
        icon: 'Skillicon14_31.png',
        description: t('nodes', 'awaken.desc'),
        maxLevel: 1,
        baseCost: 0,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: [],
        childIds: ['basic_pulse', 'integrity', 'intensity'],
        treeX: gridX(0),
        treeY: gridY(0),
        effect: function () {
            tower.awaken();
            // Show the deploy button immediately
            if (upgradeTree.isVisible()) {
                upgradeTree._showDeployButton();
            }
            if (typeof glitchFX !== 'undefined') {
                glitchFX.triggerSystemScan();
            }
        },
    },
    {
        id: 'basic_pulse',
        name: 'COGNITION',
        icon: 'Skillicon14_01.png',
        description: t('nodes', 'basic_pulse.desc'),
        popupText: t('nodes', 'basic_pulse.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['awaken'],
        childIds: ['pulse_damage', 'magnet', 'lightning_weapon', 'shockwave_weapon', 'placeholder_duo_1'],
        treeX: gridX(0),
        treeY: gridY(1),
        effect: function () {
            pulseAttack.unlock();
        },
    },
    {
        id: 'pulse_damage',
        name: 'CONCENTRATION',
        icon: 'Skillicon14_13.png',
        description: t('nodes', 'pulse_damage.desc'),
        popupText: t('nodes', 'pulse_damage.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 3,
        baseCost: 5,
        costType: 'data',
        costScaling: 'linear',
        costStep: 10,
        costStepScaling: 10,
        parents: ['basic_pulse'],
        childIds: ['pulse_expansion'],
        treeX: gridX(1),
        treeY: gridY(1),
        effect: function () {
            upgradeDispatcher.recalcPulseDamage();
        },
    },
    {
        id: 'magnet',
        name: 'CONVERGENCE',
        icon: 'Skillicon14_07.png',
        description: t('nodes', 'magnet.desc'),
        popupText: t('nodes', 'magnet.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        costType: 'insight',
        costScaling: 'static',
        costStep: 0,
        parents: ['basic_pulse'],
        childIds: ['data_compression'],
        treeX: gridX(-1),
        treeY: gridY(1),
        effect: function () {
            resourceManager.recalcPickupRadius();
        },
    },
    {
        id: 'pulse_expansion',
        name: 'SIGNAL STRENGTH',
        icon: 'Skillicon14_28.png',
        description: t('nodes', 'pulse_expansion.desc'),
        popupText: t('nodes', 'pulse_expansion.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 50,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['pulse_damage'],
        requiresMaxParent: true,
        childIds: ['packet_sniffing', 'diagnostic_analytics'],
        treeX: gridX(2),
        treeY: gridY(1),
        effect: function () {
            upgradeDispatcher.recalcPulseSize();
        },
    },
    {
        id: 'overcharge',
        name: 'OVERCHARGE',
        icon: 'Skillicon14_02.png',
        description: t('nodes', 'overcharge.desc'),
        popupText: t('nodes', 'overcharge.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 2,
        baseCost: 150,
        costType: 'data',
        costScaling: 'linear',
        costStep: 50,
        parents: ['test_defenses'],
        childIds: ['placeholder_duo_2', 'armor'],

        treeX: gridX(-1),
        treeY: gridY(4.5),
        effect: function () {
            upgradeDispatcher.recalcPulseDamage();

            if (!gameState.unlockedNodes) gameState.unlockedNodes = {};
            gameState.unlockedNodes['armor'] = true;
        },
    },
    {
        id: 'integrity',
        name: 'INTEGRITY',
        icon: 'Skillicon14_16.png',
        description: t('nodes', 'integrity.desc'),
        popupText: t('nodes', 'integrity.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 5,
        baseCost: 4,
        costType: 'data',
        costScaling: 'linear',
        costStep: 4,
        costStepScaling: 6,
        parents: ['awaken'],
        childIds: ['regen'],
        treeX: gridX(-1),
        treeY: gridY(0),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' → tower._onUpgradePurchased
        },
    },
    {
        id: 'intensity',
        name: 'INTENSITY',
        icon: 'Skillicon14_26.png',
        description: t('nodes', 'intensity.desc'),
        popupText: t('nodes', 'intensity.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 5,
        baseCost: 5,
        costType: 'data',
        costScaling: 'linear',
        costStep: 5,
        costStepScaling: 5,
        parents: ['awaken'],
        childIds: ['focus', 'prismatic_array'],
        treeX: gridX(1),
        treeY: gridY(0),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' → tower._onUpgradePurchased
        },
    },
    {
        id: 'focus',
        name: 'COVERAGE',
        icon: 'Skillicon14_23.png',
        description: t('nodes', 'focus.desc'),
        popupText: t('nodes', 'focus.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 50,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['intensity'],
        requiresMaxParent: true,
        childIds: ['diagnostic_analytics'],
        treeX: gridX(2),
        treeY: gridY(0),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' → tower._onUpgradePurchased
        },
    },
    {
        id: 'diagnostic_analytics',
        name: 'DIAGNOSTICS',
        icon: 'Skillicon14_06.png',
        description: t('nodes', 'diagnostic_analytics.desc'),
        popupText: t('nodes', 'diagnostic_analytics.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 1,
        baseCost: 100,
        costType: 'data',
        costScaling: 'static',
        parents: ['pulse_expansion', 'focus'],
        requiresMaxParent: true,
        treeX: gridX(3),
        treeY: gridY(0.5),
        effect: function () {
            // This is checked by iterationOverScreen.js
        },
    },

    {
        id: 'regen',
        name: 'AUTO-RESTORE',
        icon: 'Skillicon14_11.png',
        description: t('nodes', 'regen.desc'),
        popupText: t('nodes', 'regen.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 3,
        baseCost: 10,
        costType: 'data',
        costScaling: 'linear',
        costStep: 10,
        costStepScaling: 10,
        parents: ['integrity'],
        childIds: ['lore_1', 'system_redundancy_new'],
        treeX: gridX(-2),
        treeY: gridY(0),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' → tower._onUpgradePurchased
        },
    },


    {
        id: 'base_hp_boost',
        name: 'AUXILIARY POWER',
        icon: 'Skillicon14_11.png',
        description: t('nodes', 'base_hp_boost.desc'),
        popupText: t('nodes', 'base_hp_boost.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['security_test_2', 'overclock'],
        childIds: ['gateway_discovery'],
        treeX: gridX(-1.0),
        treeY: gridY(8.5),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' → tower._onUpgradePurchased
        },
    },
    {
        id: 'malware_siphon',
        name: 'MALWARE SIPHON',
        icon: 'Skillicon14_03.png',
        description: t('nodes', 'malware_siphon.desc'),
        popupText: t('nodes', 'malware_siphon.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['trojan_access', 'backdoor_3'],
        childIds: ['repeat_exploit'],
        treeX: gridX(3),
        treeY: gridY(6.0),
        effect: function () { },
    },
    {
        id: 'lore_1',
        name: 'ARCHIVE',
        lore: true,
        label: 'LORE',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'lore_1.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['regen'],
        childIds: [],
        treeX: gridX(-3),
        treeY: gridY(0),
        requiresMaxParent: true,
        tooltipExtraWidth: 300,
        effect: function () {
            const node = upgradeTree.getNode('lore_1');
            if (node) {
                node.description = t('nodes', 'lore_1.unlocked_desc');
            }
        },
    },
    {
        id: 'lore_2',
        name: 'ARCHIVE II',
        lore: true,
        label: 'LORE',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'lore_2.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['junk_barrier'],
        childIds: [],
        treeX: gridX(4),
        treeY: gridY(1.5),
        requiresMaxParent: true,
        tooltipExtraWidth: 300,
        effect: function () {
            const node = upgradeTree.getNode('lore_2');
            if (node) {
                node.description = t('nodes', 'lore_2.unlocked_desc');
            }
        },
    },
    {
        id: 'lore_3',
        name: 'ARCHIVE III',
        lore: true,
        label: 'LORE',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'lore_3.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['threat_response'],
        childIds: ['lore_4'],
        treeX: gridX(-4),
        treeY: gridY(4.5),
        tooltipExtraWidth: 300,
        effect: function () {
            const node = upgradeTree.getNode('lore_3');
            if (node) {
                node.description = t('nodes', 'lore_3.unlocked_desc');
            }
        },
    },
    {
        id: 'lore_4',
        name: 'ARCHIVE IV',
        lore: true,
        label: 'LORE',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'lore_4.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['lore_3'],
        childIds: ['lore_5'],
        treeX: gridX(-4.5),
        treeY: gridY(3.5),
        tooltipExtraWidth: 300,
        effect: function () {
            const node = upgradeTree.getNode('lore_4');
            if (node) {
                node.description = t('nodes', 'lore_4.unlocked_desc');
            }
        },
    },
    {
        id: 'lore_5',
        name: 'ARCHIVE V',
        lore: true,
        label: 'LORE',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'lore_5.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['lore_4'],
        childIds: ['lore_6'],
        treeX: gridX(-4.5),
        treeY: gridY(4.5),
        tooltipExtraWidth: 300,
        effect: function () {
            const node = upgradeTree.getNode('lore_5');
            if (node) {
                node.description = t('nodes', 'lore_5.unlocked_desc');
            }
        },
    },
    {
        id: 'lore_6',
        name: 'ARCHIVE VI',
        lore: true,
        label: 'LORE',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'lore_6.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['lore_5'],
        childIds: ['lore_7'],
        treeX: gridX(-4.5),
        treeY: gridY(5.5),
        tooltipExtraWidth: 300,
        effect: function () {
            const node = upgradeTree.getNode('lore_6');
            if (node) {
                node.description = t('nodes', 'lore_6.unlocked_desc');
            }
        },
    },
    {
        id: 'lore_7',
        name: 'ARCHIVE VII',
        lore: true,
        label: 'LORE',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'lore_7.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['lore_6'],
        childIds: ['lore_8'],
        treeX: gridX(-4.5),
        treeY: gridY(6.5),
        tooltipExtraWidth: 300,
        effect: function () {
            const node = upgradeTree.getNode('lore_7');
            if (node) {
                node.description = t('nodes', 'lore_7.unlocked_desc');
            }
        },
    },
    {
        id: 'lore_8',
        name: 'ARCHIVE VIII',
        lore: true,
        label: 'LORE',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'lore_8.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['lore_7'],
        childIds: ['lore_9'],
        treeX: gridX(-4.5),
        treeY: gridY(7.5),
        tooltipExtraWidth: 300,
        effect: function () {
            const node = upgradeTree.getNode('lore_8');
            if (node) {
                node.description = t('nodes', 'lore_8.unlocked_desc');
            }
        },
    },
    {
        id: 'lore_9',
        name: 'ARCHIVE IX',
        lore: true,
        label: 'LORE',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'lore_9.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['lore_8'],
        childIds: [],
        treeX: gridX(-4.5),
        treeY: gridY(8.5),
        tooltipExtraWidth: 300,
        effect: function () {
            const node = upgradeTree.getNode('lore_9');
            if (node) {
                node.description = t('nodes', 'lore_9.unlocked_desc');
            }
        },
    },

    {
        id: 'threat_response',
        name: 'RECOVERY PROTOCOL',
        icon: 'Skillicon14_27.png',
        description: t('nodes', 'threat_response.desc'),
        popupText: t('nodes', 'threat_response.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        parents: ['armor'],
        childIds: ['lore_3'],
        treeX: gridX(-3),
        treeY: gridY(4.5),
        effect: function () {
            // Logic integrated into gameInit.js listeners
        },
    },
    {
        id: 'placeholder_duo_1',
        isPlaceholder: true,
        parents: ['basic_pulse'],
        monitorsDuoTier: 1,
        childIds: ['test_defenses'],

        treeX: gridX(0),
        treeY: gridY(2.125), // Mid-point adjustment (non-clean)
        effect: function () { },
    },
    // ── Tier 1 Duo-Box: Lightning Weapon & Shockwave Weapon ──────────────
    {
        id: 'lightning_weapon',
        name: 'LIGHTNING',
        icon: 'Skillicon14_33.png',
        description: t('nodes', 'lightning_weapon.desc'),
        popupText: t('nodes', 'lightning_weapon.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        costStep: 0,
        parents: ['basic_pulse'],
        childIds: ['lightning_chain', 'lightning_boost'],
        isDuoBox: true,
        duoBoxTier: 1,
        shardId: 'lightning_weapon',
        duoSiblingId: 'shockwave_weapon',
        treeX: gridX(0) - DUO_OFFSET, // Symmetric Duo offset (standardized)
        treeY: gridY(2.5),
        effect: function () {
            lightningAttack.unlock();
            shockwaveAttack.lock();
        },
    },
    {
        id: 'shockwave_weapon',
        name: 'SHOCKWAVE',
        icon: 'Skillicon14_37.png',
        description: t('nodes', 'shockwave_weapon.desc'),
        popupText: t('nodes', 'shockwave_weapon.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        costStep: 0,
        parents: ['basic_pulse'],
        childIds: ['shockwave_amplifier', 'shockwave_resonance'],
        isDuoBox: true,
        duoBoxTier: 1,
        shardId: 'shockwave_weapon',
        duoSiblingId: 'lightning_weapon',
        treeX: gridX(0) + DUO_OFFSET, // Symmetric Duo offset (standardized)
        treeY: gridY(2.5),
        effect: function () {
            shockwaveAttack.unlock();
            lightningAttack.lock();
        },
    },
    {
        id: 'lightning_chain',
        name: 'FORK',
        icon: 'Skillicon14_40.png',
        description: t('nodes', 'lightning_chain.desc'),
        popupText: t('nodes', 'lightning_chain.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 100,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['lightning_weapon'],
        childIds: ['lightning_static_charge'],
        treeX: gridX(-1.5),
        treeY: gridY(2),
        effect: function () {
            upgradeDispatcher.recalcLightningChains();
        },
    },
    {
        id: 'lightning_boost',
        name: 'VOLTAGE',
        icon: 'Skillicon14_03.png',
        description: t('nodes', 'lightning_boost.desc'),
        popupText: t('nodes', 'lightning_boost.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 3,
        baseCost: 75,
        costType: 'data',
        costScaling: 'linear',
        costStep: 0,
        parents: ['lightning_weapon'],
        childIds: ['lightning_static_charge'],
        treeX: gridX(-1.5),
        treeY: gridY(3),
        effect: function () {
            upgradeDispatcher.recalcLightningDamage();
        },
    },
    {
        id: 'lightning_static_charge',
        name: 'INITIAL SHOCK',
        icon: 'Skillicon14_10.png',
        description: t('nodes', 'lightning_static_charge.desc'),
        popupText: t('nodes', 'lightning_static_charge.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 2,
        baseCost: 100,
        costType: 'data',
        costScaling: 'linear',
        costStep: 100,
        parents: ['lightning_boost', 'lightning_chain'],
        requiresMaxParent: true,
        childIds: [],
        treeX: gridX(-2.5),
        treeY: gridY(2.5),
        effect: function () {
            upgradeDispatcher.recalcLightningDamage();
        },
    },
    {
        id: 'shockwave_amplifier',
        name: 'AMPLIFIER',
        icon: 'Skillicon14_28.png',
        description: t('nodes', 'shockwave_amplifier.desc'),
        popupText: t('nodes', 'shockwave_amplifier.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 100,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['shockwave_weapon'],
        childIds: ['shockwave_seismic_crush'],
        treeX: gridX(1.5),
        treeY: gridY(2),
        effect: function () {
            upgradeDispatcher.recalcShockwaveStats();
        },
    },
    {
        id: 'shockwave_resonance',
        name: 'GRAV-LOCK',
        icon: 'Skillicon14_03.png',
        description: t('nodes', 'shockwave_resonance.desc'),
        maxLevel: 1,
        baseCost: 100,
        costType: 'data',
        costScaling: 'static',
        parents: ['shockwave_weapon'],
        childIds: ['shockwave_seismic_crush'],
        treeX: gridX(1.5),
        treeY: gridY(3),
        effect: function () {
            upgradeDispatcher.recalcShockwaveStats();
        },
    },
    {
        id: 'shockwave_seismic_crush',
        name: 'SEISMIC CRUSH',
        icon: 'Skillicon14_19.png',
        description: t('nodes', 'shockwave_seismic_crush.desc'),
        popupText: t('nodes', 'shockwave_seismic_crush.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 2,
        baseCost: 150,
        costType: 'data',
        costScaling: 'linear',
        costStep: 150,
        parents: ['shockwave_amplifier', 'shockwave_resonance'],
        requiresMaxParent: true,
        childIds: [],
        treeX: gridX(2.5),
        treeY: gridY(2.5),
        effect: function () {
            upgradeDispatcher.recalcShockwaveStats();
        },
    },
    {
        id: 'armor',
        name: 'RESILIENCE',
        icon: 'Skillicon14_18.png',
        description: t('nodes', 'armor.desc'),
        popupText: t('nodes', 'armor.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['overcharge'],
        treeX: gridX(-2),
        treeY: gridY(4.5),
        childIds: ['threat_response', 'data_chest_unlock'],
        effect: function () {
            // Recalculated via 'upgradePurchased' → tower._onUpgradePurchased
        },
    },
    {
        id: 'data_chest_unlock',
        name: 'DATA HUNTER',
        icon: 'Skillicon14_38.png',
        description: t('nodes', 'data_chest_unlock.desc'),
        popupText: t('nodes', 'data_chest_unlock.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        costType: 'insight',
        costScaling: 'static',
        parents: ['armor'],
        childIds: ['junk_data_2'],
        treeX: gridX(-2.5),
        treeY: gridY(3.5),
        effect: function () { },
    },
    {
        id: 'system_redundancy_new',
        name: 'SYSTEM REDUNDANCY',
        icon: 'Skillicon14_18.png',
        description: t('nodes', 'system_redundancy_new.desc'),
        popupText: t('nodes', 'system_redundancy_new.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 1,
        baseCost: 100,
        costType: 'data',
        costScaling: 'static',
        parents: ['regen'],
        childIds: [],
        treeX: gridX(-3.0),
        treeY: gridY(1.0),
        effect: function () { },
    },
    {
        id: 'overclock',
        name: 'OVERCLOCK',
        icon: 'Skillicon14_05.png',
        description: t('nodes', 'overclock.desc'),
        popupText: t('nodes', 'overclock.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 4,
        baseCost: 50,
        costType: 'data',
        costScaling: 'linear',
        costStep: 50,
        costStepScaling: 10,
        parents: ['privilege_escalation_3'],
        childIds: ['base_hp_boost'],
        treeX: gridX(0.0),
        treeY: gridY(8.5),
        effect: function () {
            // Recalculated via messageBus 'upgradePurchased' → tower._onUpgradePurchased
        },
    },
    {
        id: 'trojan_access',
        name: 'TROJAN PAYLOAD',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'trojan_access.desc'),
        popupText: t('nodes', 'trojan_access.popup'),
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        parents: ['backdoor_2', 'two_step_auth'],
        childIds: ['volatile_payload', 'malware_siphon'],
        treeX: gridX(3),
        treeY: gridY(5.0),
        effect: function () { },
    },
    {
        id: 'volatile_payload',
        name: 'VOLATILE PAYLOAD',
        icon: 'Skillicon14_10.png',
        description: t('nodes', 'volatile_payload.desc'),
        popupText: t('nodes', 'volatile_payload.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 5,
        baseCost: 150,
        costType: 'data',
        costScaling: 'linear',
        costStep: 50,
        costStepScaling: 8,
        parents: ['trojan_access'],
        childIds: [],
        treeX: gridX(2.0),
        treeY: gridY(5.5),
        effect: function () { },
    },
    {
        id: 'prismatic_array',
        name: 'PRISMATIC ARRAY',
        icon: 'Skillicon14_30.png',
        description: t('nodes', 'prismatic_array.desc'),
        popupText: t('nodes', 'prismatic_array.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 5,
        baseCost: 50,
        costType: 'data',
        costScaling: 'linear',
        costStep: 50,
        costStepScaling: 12,
        parents: ['intensity'],
        childIds: [],
        treeX: gridX(2.0),
        treeY: gridY(-1.0),
        effect: function () {
            // Recalculated via normal gameplay checks
        },
    },
    {
        id: 'test_defenses',
        name: 'SANDBOX MODE',
        icon: 'Skillicon14_05.png',
        description: t('nodes', 'test_defenses.desc'),
        popupText: t('nodes', 'test_defenses.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 100,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['placeholder_duo_1'],
        childIds: ['overcharge', 'security_test_1'],
        treeX: gridX(0),
        treeY: gridY(4),
        effect: function () {
            gameState.upgrades.test_defenses_unlocked = true;
            if (typeof gameHUD !== 'undefined' && gameHUD.refreshTestDefensesButton) {
                gameHUD.refreshTestDefensesButton();
            }
        },
    },
    {
        id: 'data_compression',
        name: 'DATA COMPRESSION',
        icon: 'Skillicon14_20.png',
        description: t('nodes', 'data_compression.desc'),
        popupText: t('nodes', 'data_compression.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        costType: 'insight',
        costScaling: 'static',
        costStep: 0,
        parents: ['magnet'],
        childIds: [],
        treeX: gridX(-2),
        treeY: gridY(1),
        effect: function () { },
    },
    {
        id: 'security_test_1',
        name: 'SECURITY TEST',
        icon: 'Skillicon14_38.png',
        description: t('nodes', 'security_test_1.desc'),
        popupText: t('nodes', 'security_test_1.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 300,
        costType: 'data',
        costScaling: 'static',
        parents: ['test_defenses'],
        childIds: ['two_step_auth'],
        treeX: gridX(1),
        treeY: gridY(4.5),
        tooltipExtraWidth: 40,
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(300);
            }
        },
    },
    {
        id: 'two_step_auth',
        name: 'TWO-STEP AUTH',
        icon: 'Skillicon14_10.png',
        description: t('nodes', 'two_step_auth.desc'),
        popupText: t('nodes', 'two_step_auth.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        costType: 'insight',
        costScaling: 'static',
        parents: ['security_test_1'],
        childIds: ['trojan_access'],
        tooltipExtraWidth: 40,
        treeX: gridX(2),
        treeY: gridY(4.5),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(100);
            }
        },
    },
    {
        id: 'packet_sniffing',
        name: 'PACKET SNIFFING',
        icon: 'Skillicon14_01.png',
        description: t('nodes', 'packet_sniffing.desc'),
        popupText: t('nodes', 'packet_sniffing.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        costType: 'insight',
        costScaling: 'static',
        parents: ['pulse_expansion'],
        childIds: ['junk_barrier'],
        treeX: gridX(3),
        treeY: gridY(1.5),
        effect: function () {
            upgradeDispatcher.recalcPacketSniffing();
        },
    },
    {
        id: 'junk_barrier',
        name: 'UNSORTED LOGS',
        icon: 'Skillicon14_06.png',
        description: t('nodes', 'junk_barrier.desc'),
        maxLevel: 5,
        baseCost: 10,
        costType: 'data',
        costScaling: 'static',
        parents: ['packet_sniffing'],
        childIds: ['forgotten_backdoor', 'lore_2'],
        treeX: gridX(3.5),
        treeY: gridY(2.5),
        tooltipExtraWidth: 60,
        effect: function () {
            // No longer refunds anything
        },
    },
    {
        id: 'forgotten_backdoor',
        name: 'FORGOTTEN BACKDOOR',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'forgotten_backdoor.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        requiresMaxParent: true,
        costScaling: 'static',
        parents: ['junk_barrier'],
        childIds: ['backdoor_2', 'zero_day_exploit'],
        treeX: gridX(4),
        treeY: gridY(3.5),
        effect: function () { },
    },

    {
        id: 'junk_data_2',
        name: 'JUNK DATA',
        icon: 'Skillicon14_12.png',
        description: t('nodes', 'junk_data_2.desc'),
        popupText: t('nodes', 'junk_data_2.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 10,
        baseCost: 2,
        costType: 'data',
        costScaling: 'static',
        requiresMaxParent: true,
        parents: ['data_chest_unlock'],
        childIds: [],
        treeX: gridX(-3.5),
        treeY: gridY(3.5),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(10);
            }
        },
    },
    {
        id: 'backdoor_2',
        name: 'BACKDOOR 2',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'backdoor_2.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['forgotten_backdoor'],
        childIds: ['backdoor_3', 'trojan_access'],
        treeX: gridX(4),
        treeY: gridY(4.5),
        effect: function () { },
    },
    {
        id: 'backdoor_3',
        name: 'BACKDOOR 3',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'backdoor_3.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['backdoor_2'],
        childIds: ['backdoor_4', 'malware_siphon'],
        treeX: gridX(4),
        treeY: gridY(5.5),
        effect: function () { },
    },
    {
        id: 'backdoor_4',
        name: 'BACKDOOR 4',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'backdoor_4.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['backdoor_3'],
        childIds: ['unsecured_files', 'repeat_exploit'],
        treeX: gridX(4),
        treeY: gridY(6.5),
        effect: function () { },
    },
    {
        id: 'repeat_exploit',
        name: 'REPEAT EXPLOIT',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'repeat_exploit.desc'),
        popupText: t('nodes', 'repeat_exploit.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['backdoor_4', 'malware_siphon'],
        childIds: ['injection_attack', 'unsecured_wallet'],
        treeX: gridX(3.0),
        treeY: gridY(7.0),
        effect: function () {
            upgradeDispatcher.recalcRepeatExploit();
        },
    },
    {
        id: 'unsecured_wallet',
        name: 'UNSECURE WALLET',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'unsecured_wallet.desc'),
        popupText: t('nodes', 'unsecured_wallet.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        costType: 'insight',
        costScaling: 'static',
        parents: ['repeat_exploit'],
        childIds: [],
        tooltipExtraWidth: 100,
        treeX: gridX(3.0),
        treeY: gridY(8.0),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addCoin(1);
            }
        },
    },


    {
        id: 'privilege_escalation_3',
        name: 'PRIVILEGE ESCALATION III',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'privilege_escalation_3.desc'),
        maxLevel: 1,
        baseCost: 0,
        costType: 'data',
        costScaling: 'static',
        parents: ['injection_attack', 'shell_access'],
        childIds: ['placeholder_duo_3', 'laser', 'artillery', 'overclock'],
        treeX: gridX(1.0),
        treeY: gridY(8.0),
        effect: function () { },
    },
    {
        id: 'placeholder_duo_3',
        isPlaceholder: true,
        parents: ['privilege_escalation_3'],
        monitorsDuoTier: 3,
        childIds: ['security_test_3'],
        treeX: gridX(1.0),
        treeY: gridY(9.5),
        effect: function () { },
    },
    {
        id: 'laser',
        name: 'LASER',
        icon: 'Skillicon14_06.png',
        description: t('nodes', 'laser.desc'),
        popupText: t('nodes', 'laser.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        parents: ['privilege_escalation_3'],
        childIds: ['laser_duration'],
        isDuoBox: true,
        duoBoxTier: 3,
        shardId: 'laser',
        duoSiblingId: 'artillery',
        treeX: gridX(1.0) - DUO_OFFSET,
        treeY: gridY(9.5),
        effect: function () {
            if (typeof laserAttack !== 'undefined') laserAttack.unlock();
            artilleryAttack.lock();
        },
    },
    {
        id: 'artillery',
        name: 'ARTILLERY',
        icon: 'Skillicon14_11.png',
        description: t('nodes', 'artillery.desc'),
        popupText: t('nodes', 'artillery.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        duoSiblingId: 'laser',
        treeX: gridX(1.0) + DUO_OFFSET,
        treeY: gridY(9.5),
        parents: ['privilege_escalation_3'],
        childIds: ['artillery_shells', 'artillery_first_strike'],
        isDuoBox: true,
        duoBoxTier: 3,
        shardId: 'artillery',
        effect: function () {
            artilleryAttack.unlock();
            if (typeof laserAttack !== 'undefined') laserAttack.lock();
        },
    },
    {
        id: 'laser_duration',
        name: 'DURATION',
        icon: 'Skillicon14_05.png',
        description: t('nodes', 'laser_duration.desc'),
        popupText: t('nodes', 'laser_duration.popup'),
        maxLevel: 5,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['laser'],
        childIds: ['laser_aperture', 'laser_incendiary'],
        treeX: gridX(1.0 - 1.5),
        treeY: gridY(9.5),
        effect: function () {
            upgradeDispatcher.recalcLaser();
        },
    },
    {
        id: 'laser_aperture',
        name: 'PHOTON SATURATION',
        icon: 'Skillicon14_22.png',
        description: t('nodes', 'laser_aperture.desc'),
        popupText: t('nodes', 'laser_aperture.popup'),
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        parents: ['laser_duration'],
        childIds: ['laser_twin_beams'],
        treeX: gridX(1.0 - 1.5 - 1.0),
        treeY: gridY(9.5),
        effect: function () {
            upgradeDispatcher.recalcLaser();
        },
    },
    {
        id: 'laser_incendiary',
        name: 'INCENDIARY',
        icon: 'Skillicon14_26.png',
        description: t('nodes', 'laser_incendiary.desc'),
        popupText: t('nodes', 'laser_incendiary.popup'),
        maxLevel: 2,
        baseCost: 150,
        costType: 'data',
        costScaling: 'linear',
        costStep: 150,
        parents: ['laser_duration'],
        childIds: ['laser_twin_beams'],
        treeX: gridX(1.0 - 1.5),
        treeY: gridY(10.5),
        effect: function () {
            upgradeDispatcher.recalcLaser();
        },
    },
    {
        id: 'laser_twin_beams',
        name: 'TWIN BEAMS',
        icon: 'Skillicon14_30.png',
        description: t('nodes', 'laser_twin_beams.desc'),
        popupText: t('nodes', 'laser_twin_beams.popup'),
        maxLevel: 1,
        baseCost: 300,
        costType: 'data',
        costScaling: 'static',
        parents: ['laser_aperture', 'laser_incendiary'],
        childIds: [],
        treeX: gridX(-1.5),
        treeY: gridY(10.5),
        effect: function () {
            upgradeDispatcher.recalcLaser();
        },
    },
    {
        id: 'artillery_volley',
        name: 'TRIPLE VOLLEY',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'artillery_volley.desc'),
        popupText: t('nodes', 'artillery_volley.popup'),
        maxLevel: 1,
        baseCost: 400,
        costType: 'data',
        costScaling: 'static',
        parents: ['artillery_shells'],
        childIds: [],
        treeX: gridX(3.5),
        treeY: gridY(10.0),
        requiresMaxParent: true,
        effect: function () { upgradeDispatcher.recalcArtillery(); },
    },

    {
        id: 'artillery_shells',
        name: 'HIGH EXPLOSIVE',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'artillery_shells.desc'),
        popupText: t('nodes', 'artillery_shells.popup'),
        maxLevel: 3,
        baseCost: 150,
        costType: 'data',
        costScaling: 'linear',
        costStep: 0,
        parents: ['artillery'],
        childIds: ['artillery_volley'],
        treeX: gridX(2.5),
        treeY: gridY(10.0),
        effect: function () { upgradeDispatcher.recalcArtillery(); },
    },
    {
        id: 'artillery_first_strike',
        name: 'FIRST STRIKE',
        icon: 'Skillicon14_31.png',
        description: t('nodes', 'artillery_first_strike.desc'),
        popupText: t('nodes', 'artillery_first_strike.popup'),
        maxLevel: 3,
        baseCost: 150,
        costType: 'data',
        costScaling: 'linear',
        costStep: 0,
        parents: ['artillery'],
        childIds: ['artillery_stun'],
        treeX: gridX(2.5),
        treeY: gridY(9.0),
        effect: function () { upgradeDispatcher.recalcArtillery(); },
    },
    {
        id: 'artillery_stun',
        name: 'SHELLSHOCKED',
        icon: 'Skillicon14_10.png',
        description: t('nodes', 'artillery_stun.desc'),
        popupText: t('nodes', 'artillery_stun.popup'),
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        parents: ['artillery_first_strike'],
        childIds: [],
        treeX: gridX(3.5),
        treeY: gridY(9.0),
        effect: function () { upgradeDispatcher.recalcArtillery(); },
    },
    {
        id: 'shell_access',
        name: 'SHELL ACCESS',
        icon: 'Skillicon14_34.png',
        description: t('nodes', 'shell_access.desc'),
        maxLevel: 1,
        baseCost: 250,
        costType: 'data',
        costScaling: 'static',
        parents: ['security_test_2'],
        childIds: ['privilege_escalation_3'],
        treeX: gridX(0.0),
        treeY: gridY(7.5),
        popupText: t('nodes', 'shell_access.popup'),
        popupColor: COLORS.COMBAT,
        effect: function () {
            // Recalculated by tower.js listener
        },
    },

    {
        id: 'unsecured_files',
        name: 'UNSECURED FILES',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'unsecured_files.desc'),
        popupText: '+15 DATA',
        popupColor: COLORS.RESOURCE,
        maxLevel: 10,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        parents: ['backdoor_4'],
        childIds: [],
        treeX: gridX(4),
        treeY: gridY(7.5),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(15);
            }
        },
    },
    {
        id: 'injection_attack',
        name: 'INJECTION ATTACK',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'injection_attack.desc'),
        popupText: t('nodes', 'injection_attack.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 3,
        baseCost: 150,
        costType: 'data',
        costScaling: 'linear',
        costStep: 100,
        parents: ['repeat_exploit'],
        childIds: ['privilege_escalation_3'],
        treeX: gridX(2.0),
        treeY: gridY(7.5),
        effect: function () { },
    },
    {
        id: 'zero_day_exploit',
        name: 'ZERO-DAY EXPLOIT',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'zero_day_exploit.desc'),
        popupText: t('nodes', 'zero_day_exploit.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['forgotten_backdoor'],
        childIds: [],
        treeX: gridX(3),
        treeY: gridY(3.5),
        effect: function () { },
    },
    {
        id: 'placeholder_duo_2',
        isPlaceholder: true,
        parents: ['overcharge'],
        monitorsDuoTier: 2,
        childIds: ['manual_pulse', 'wide_pulse', 'security_test_2'],
        treeX: gridX(-1),
        treeY: gridY(6.0),
        effect: function () { },
    },
    {
        id: 'security_test_2',
        name: 'SECURITY TEST 2',
        icon: 'Skillicon14_38.png',
        description: t('nodes', 'security_test_2.desc'),
        maxLevel: 1,
        baseCost: 600,
        costType: 'data',
        costScaling: 'static',
        parents: ['placeholder_duo_2'],
        childIds: ['base_hp_boost', 'shell_access', 'gateway_discovery'],
        treeX: gridX(-1),
        treeY: gridY(7.5),
        tooltipExtraWidth: 60,
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(500);
            }
        },
    },
    {
        id: 'manual_pulse',
        name: 'MANUAL PROTOCOL',
        icon: 'Skillicon14_34.png',
        description: t('nodes', 'manual_pulse.desc'),
        popupText: t('nodes', 'manual_pulse.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        parents: ['overcharge'],
        childIds: ['manual_pulse_child_1'],
        isDuoBox: true,
        duoBoxTier: 2,
        shardId: 'manual_pulse',
        duoSiblingId: 'wide_pulse',
        treeX: gridX(-1) - DUO_OFFSET, // Symmetric Duo offset (standardized)
        treeY: gridY(6),
        effect: function () {
            upgradeDispatcher.recalcPulseMode();
            upgradeDispatcher.recalcPulseSize();
        },
    },
    {
        id: 'wide_pulse',
        name: 'BROADCAST PROTOCOL',
        icon: 'Skillicon14_28.png',
        description: t('nodes', 'wide_pulse.desc'),
        popupText: t('nodes', 'wide_pulse.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        parents: ['overcharge'],
        childIds: ['wide_pulse_child_1', 'aftershock'],
        isDuoBox: true,
        duoBoxTier: 2,
        shardId: 'wide_pulse',
        duoSiblingId: 'manual_pulse',
        treeX: gridX(-1) + DUO_OFFSET, // Symmetric Duo offset (standardized)
        treeY: gridY(6),
        effect: function () {
            upgradeDispatcher.recalcPulseSize();
            upgradeDispatcher.recalcPulseMode();
        },
    },
    {
        id: 'manual_pulse_child_1',
        name: 'CHARGE BUFFER',
        icon: 'Skillicon14_33.png',
        description: t('nodes', 'manual_pulse_child_1.desc'),
        popupText: t('nodes', 'manual_pulse_child_1.popup'),
        maxLevel: 3,
        baseCost: 100,
        costType: 'data',
        costScaling: 'linear',
        costStep: 0,
        parents: ['manual_pulse'],
        childIds: ['manual_pulse_child_1_1', 'manual_pulse_child_1_2'],
        treeX: gridX(-2.5),
        treeY: gridY(6),
        effect: function () {
            upgradeDispatcher.recalcPulseCharges();
        },
    },
    {
        id: 'manual_pulse_child_1_1',
        name: 'ISOLATION',
        icon: 'Skillicon14_25.png',
        description: t('nodes', 'manual_pulse_child_1_1.desc'),
        popupText: t('nodes', 'manual_pulse_child_1_1.popup'),
        maxLevel: 4,
        baseCost: 100,
        costType: 'data',
        costScaling: 'linear',
        costStep: 50,
        parents: ['manual_pulse_child_1'],
        childIds: [],
        treeX: gridX(-3.5),
        treeY: gridY(6.5),
        effect: function () {
            upgradeDispatcher.recalcPulseDamage();
        },
    },
    {
        id: 'manual_pulse_child_1_2',
        name: 'RELOAD EFFICIENCY',
        icon: 'Skillicon14_17.png',
        description: t('nodes', 'manual_pulse_child_1_2.desc'),
        popupText: t('nodes', 'manual_pulse_child_1_2.popup'),
        maxLevel: 1,
        baseCost: 100,
        costType: 'data',
        costScaling: 'static',
        parents: ['manual_pulse_child_1'],
        childIds: [],
        treeX: gridX(-3.5),
        treeY: gridY(5.5),
        effect: function () {
            upgradeDispatcher.recalcPulseReload();
        },
    },
    {
        id: 'wide_pulse_child_1',
        name: 'AREA SATURATION',
        icon: 'Skillicon14_22.png',
        description: t('nodes', 'wide_pulse_child_1.desc'),
        popupText: t('nodes', 'wide_pulse_child_1.popup'),
        maxLevel: 4,
        baseCost: 100,
        costType: 'data',
        costScaling: 'linear',
        costStep: 0,
        parents: ['wide_pulse'],
        childIds: ['colossal_cursor'],
        treeX: gridX(0.5),
        treeY: gridY(6.5),
        effect: function () {
            upgradeDispatcher.recalcPulseDamage();
        },
    },
    {
        id: 'aftershock',
        name: 'AFTERSHOCK',
        icon: 'Skillicon14_21.png',
        description: t('nodes', 'aftershock.desc'),
        popupText: t('nodes', 'aftershock.popup'),
        popupColor: COLORS.DAMAGE,
        maxLevel: 3,
        baseCost: 100,
        costType: 'data',
        costScaling: 'linear',
        costStep: 0,
        parents: ['wide_pulse'],
        childIds: [],
        treeX: gridX(0.5),
        treeY: gridY(5.5),
        effect: function () {
            upgradeDispatcher.recalcAftershock();
        },
    },
    {
        id: 'colossal_cursor',
        name: 'COLOSSAL CURSOR',
        icon: 'Skillicon14_14.png',
        description: t('nodes', 'colossal_cursor.desc'),
        popupText: t('nodes', 'colossal_cursor.popup'),
        popupColor: COLORS.UPGRADE,
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        parents: ['wide_pulse_child_1'],
        childIds: [],
        treeX: gridX(1.5),
        treeY: gridY(6.5),
        requiresMaxParent: true,
        effect: function () {
            upgradeDispatcher.recalcPulseSize();
        },
    },
    {
        id: 'system_redundancy_placeholder',
        name: 'STRAY LOGS I',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'system_redundancy_placeholder.desc'),
        popupText: t('nodes', 'system_redundancy_placeholder.popup'),
        maxLevel: 1,
        baseCost: 0,
        costType: 'data',
        parents: ['gateway_discovery'],
        childIds: ['stray_logs_child_above'],
        treeX: gridX(-2.5),
        treeY: gridY(9.0),
        effect: function () { },
    },
    {
        id: 'gateway_discovery',
        name: 'GATEWAY DISCOVERY',
        icon: 'Skillicon14_38.png',
        description: t('nodes', 'gateway_discovery.desc'),
        popupText: t('nodes', 'gateway_discovery.popup'),
        maxLevel: 1,
        baseCost: 10,
        costType: 'data',
        parents: ['security_test_2', 'base_hp_boost'],
        childIds: ['system_redundancy_placeholder', 'physical_anchor', 'coin_mine_unlock'],
        treeX: gridX(-2.0),
        treeY: gridY(8.0),
        effect: function () { },
    },
    {
        id: 'security_test_3',
        name: 'SECURITY TEST 3',
        icon: 'Skillicon14_38.png',
        description: t('nodes', 'security_test_3.desc'),
        popupText: t('nodes', 'security_test_3.popup'),
        maxLevel: 1,
        baseCost: 1000,
        costType: 'data',
        costScaling: 'static',
        parents: ['placeholder_duo_3'],
        childIds: [],
        treeX: gridX(1.0),
        treeY: gridY(11.0),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(1000);
            }
        },
    },
    {
        id: 'stray_logs_child_above',
        name: 'STRAY LOGS III',
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'stray_logs_child_above.desc'),
        popupText: t('nodes', 'stray_logs_child_above.popup'),
        maxLevel: 1,
        baseCost: 0,
        costType: 'data',
        parents: ['system_redundancy_placeholder'],
        childIds: [],
        treeX: gridX(-3.0),
        treeY: gridY(10.0),
        effect: function () { },
    },
    {
        id: 'coin_mine_unlock',
        name: 'COIN MINE',
        icon: 'Skillicon14_35.png',
        description: t('nodes', 'coin_mine_unlock.desc'),
        popupText: t('nodes', 'coin_mine_unlock.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 0,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['gateway_discovery'],
        childIds: [],
        treeX: gridX(-3.0),
        treeY: gridY(8.0),
        effect: function () {
            if (typeof upgradeTree !== 'undefined') {
                upgradeTree._showCoinMineButton();
            }
        },
    },
    {
        id: 'physical_anchor',
        name: 'PURCHASE SERVERS',
        icon: 'Skillicon14_16.png',
        description: t('nodes', 'physical_anchor.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'coin',
        costScaling: 'static',
        parents: ['gateway_discovery'],
        childIds: [],
        treeX: gridX(-2.5),
        treeY: gridY(7.0),
        popupText: t('nodes', 'physical_anchor.popup'),
        popupColor: COLORS.UTILITY,
        effect: function () {
            // Stats recalculated by tower.js listener
        },
    },
];
