// nodeDefs.js â€” Upgrade Tree upgrade definitions.
// Centralized node data for the upgrade tree.

// Tree Layout Constants
const TREE_CENTER_X = 400; // Half of 800px panel width
const TREE_START_Y = 740;
const TREE_UNIT_X = 100;
const TREE_UNIT_Y = 100;
const DUO_OFFSET = 30; // Standard offset for choice nodes

// Theme Colors for Popups/Effects
const COLORS = {
    COMBAT: '#' + GAME_CONSTANTS.COLOR_HOSTILE.toString(16).padStart(6, '0'),
    UTILITY: '#' + GAME_CONSTANTS.COLOR_FRIENDLY.toString(16).padStart(6, '0'),
    RESOURCE: '#' + GAME_CONSTANTS.COLOR_RESOURCE.toString(16).padStart(6, '0'),
    HEALTH: '#87FF02',
    LORE: '#a2a2a2',
    COIN: '#00FF00'
};

// Grid Helpers
const gridX = (units) => TREE_CENTER_X + TREE_UNIT_X * units;
const gridY = (units) => TREE_START_Y - TREE_UNIT_Y * units;

const NODE_DEFS = [
    {
        id: 'awaken',
        name: t('nodes', 'awaken.name'),
        label: t('nodes', 'awaken.label'),
        icon: 'Skillicon14_31.png',
        description: t('nodes', 'awaken.desc'),
        maxLevel: 1,
        baseCost: 0,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: [],
        childIds: ['automated_defense', 'integrity', 'focus', 'cheat'],
        treeX: gridX(0),
        treeY: gridY(0),
        effect: function () {
            tower.awaken();
            pulseAttack.unlock();
            // Show the deploy button immediately
            if (upgradeTree.isVisible()) {
                upgradeTree._showDeployButton();
            }
            if (typeof glitchFX !== 'undefined') {
                glitchFX.triggerSystemScan();
            }
        },
    },
    {
        id: 'cheat',
        name: t('nodes', 'cheat.name'),
        icon: 'Skillicon14_07.png',
        description: t('nodes', 'cheat.desc'),
        popupText: t('nodes', 'cheat.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 0,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['awaken'],
        childIds: ['prismatic_array', 'backup_server', 'lore_3', 'lore_6', 'lore_7', 'lore_8', 'lore_9', 'zero_day_exploit', 'two_step_auth', 'unsecured_files', 'impact', 'completionist'],
        treeX: gridX(0),
        treeY: gridY(-1.5),
        effect: function () {
            resourceManager.addData(5000);
            resourceManager.addInsight(3);
            resourceManager.addShard(2);
            resourceManager.addCoin(10);
            if (typeof tower !== 'undefined') {
                tower.recalcStats();
                tower.heal(10);
            }
        },
    },
    {
        id: 'backup_server',
        name: t('nodes', 'backup_server.name'),
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'backup_server.desc'),
        popupText: t('nodes', 'backup_server.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['cheat'],
        childIds: ['restore_point'],
        treeX: gridX(-1),
        treeY: gridY(-2.0),
        effect: function () { },
    },
    {
        id: 'restore_point',
        name: t('nodes', 'restore_point.name'),
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'restore_point.desc'),
        popupText: t('nodes', 'restore_point.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 1,
        baseCost: 1,
        costType: 'insight',
        costScaling: 'static',
        parents: ['backup_server'],
        childIds: [],
        treeX: gridX(-1.5),
        treeY: gridY(-2.5),
        effect: function () { },
    },
    {
        id: 'peak_traffic',
        name: t('nodes', 'peak_traffic.name'),
        icon: 'Skillicon14_03.png',
        description: t('nodes', 'peak_traffic.desc'),
        popupText: t('nodes', 'peak_traffic.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        costType: 'insight',
        costScaling: 'static',
        parents: ['bomb_2'],
        childIds: ['junk_data_2'],
        treeX: gridX(-4.0),
        treeY: gridY(1.0),
        effect: function () { },
    },
    {
        id: 'automated_defense',
        name: t('nodes', 'automated_defense.name'),
        icon: 'Skillicon14_03.png',
        description: t('nodes', 'automated_defense.desc'),
        popupText: t('nodes', 'automated_defense.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['awaken'],
        childIds: ['intensity', 'magnet', 'lightning_weapon', 'shockwave_weapon', 'placeholder_duo_1'],
        treeX: gridX(0),
        treeY: gridY(1),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' -> tower._onUpgradePurchased
        },
    },
    {
        id: 'focus',
        name: t('nodes', 'focus.name'),
        icon: 'Skillicon14_02.png',
        description: t('nodes', 'focus.desc'),
        popupText: t('nodes', 'focus.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 3,
        baseCost: 5,
        costType: 'data',
        costScaling: 'linear',
        costStep: 10,
        parents: ['awaken'],
        childIds: ['pulse_expansion'],
        treeX: gridX(1),
        treeY: gridY(0),
        effect: function () {
            upgradeDispatcher.recalcPulseDamage();
        },
    },
    {
        id: 'magnet',
        name: t('nodes', 'magnet.name'),
        icon: 'Skillicon14_07.png',
        description: t('nodes', 'magnet.desc'),
        popupText: t('nodes', 'magnet.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 2,
        baseCost: 1,
        label: 'INSIGHT',
        costType: 'insight',
        costScaling: 'static',
        costStep: 0,
        parents: ['automated_defense'],
        childIds: ['test_defenses'],
        treeX: gridX(-1),
        treeY: gridY(1),
        effect: function () {
            resourceManager.recalcPickupRadius();
        },
    },
    {
        id: 'pulse_expansion',
        name: t('nodes', 'pulse_expansion.name'),
        icon: 'Skillicon14_28.png',
        description: t('nodes', 'pulse_expansion.desc'),
        popupText: t('nodes', 'pulse_expansion.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 40,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['focus'],
        requiresMaxParent: true,
        childIds: ['bomb'],
        treeX: gridX(2),
        treeY: gridY(0),
        effect: function () {
            upgradeDispatcher.recalcPulseSize();
        },
    },
    {
        id: 'impact',
        name: t('nodes', 'impact.name'),
        icon: 'Skillicon14_02.png',
        description: t('nodes', 'impact.desc'),
        popupText: t('nodes', 'impact.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 2,
        baseCost: 100,
        costType: 'data',
        costScaling: 'linear',
        costStep: 100,
        parents: ['cheat'],
        childIds: ['root_access'],

        treeX: gridX(-2.5),
        treeY: gridY(-1.5),
        effect: function () {
            upgradeDispatcher.recalcPulseDamage();
        },
    },
    {
        id: 'integrity',
        name: t('nodes', 'integrity.name'),
        icon: 'Skillicon14_16.png',
        description: t('nodes', 'integrity.desc'),
        popupText: t('nodes', 'integrity.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 4,
        baseCost: 4,
        costType: 'data',
        costScaling: 'linear',
        costStep: 8,
        parents: ['awaken'],
        childIds: ['bug_report', 'iterative_growth'],
        treeX: gridX(-1),
        treeY: gridY(0),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' â†’ tower._onUpgradePurchased
        },
    },
    {
        id: 'iterative_growth',
        name: t('nodes', 'iterative_growth.name'),
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'iterative_growth.desc'),
        popupText: t('nodes', 'iterative_growth.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 1,
        baseCost: 50,
        costType: 'data',
        costScaling: 'static',
        parents: ['integrity'],
        requiresMaxParent: true,
        childIds: [],
        treeX: gridX(-1),
        treeY: gridY(-1),
        effect: function () { },
    },
    {
        id: 'intensity',
        name: t('nodes', 'intensity.name'),
        icon: 'Skillicon14_26.png',
        description: t('nodes', 'intensity.desc'),
        popupText: t('nodes', 'intensity.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 3,
        baseCost: 10,
        costType: 'data',
        costScaling: 'linear',
        costStep: 0,
        costStepScaling: 10,
        parents: ['automated_defense'],
        childIds: ['coverage'],
        treeX: gridX(1),
        treeY: gridY(1),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' â†’ tower._onUpgradePurchased
        },
    },
    {
        id: 'coverage',
        name: t('nodes', 'coverage.name'),
        icon: 'Skillicon14_23.png',
        description: t('nodes', 'coverage.desc'),
        popupText: t('nodes', 'coverage.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 40,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['intensity'],
        requiresMaxParent: true,
        childIds: ['packet_sniffing', 'bomb'],
        treeX: gridX(2),
        treeY: gridY(1),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' â†’ tower._onUpgradePurchased
        },
    },
    {
        id: 'diagnostic_analytics',
        name: t('nodes', 'diagnostic_analytics.name'),
        icon: 'Skillicon14_06.png',
        description: t('nodes', 'diagnostic_analytics.desc'),
        popupText: t('nodes', 'diagnostic_analytics.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 1,
        baseCost: 20,
        costType: 'data',
        costScaling: 'static',
        parents: ['armor'],
        childIds: ['data_compression', 'placeholder_duo_3', 'laser', 'artillery'],
        requiresMaxParent: true,
        treeX: gridX(-3.5),
        treeY: gridY(5),
        effect: function () {
            // This is checked by iterationOverScreen.js
        },
    },

    {
        id: 'regen',
        name: t('nodes', 'regen.name'),
        icon: 'Skillicon14_11.png',
        description: t('nodes', 'regen.desc'),
        popupText: t('nodes', 'regen.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 1,
        baseCost: 2,
        costType: 'coin',
        costScaling: 'static',
        costStep: 20,
        parents: ['armor'],
        childIds: [],
        treeX: gridX(-1.5),
        treeY: gridY(5),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' â†’ tower._onUpgradePurchased
        },
    },
    {
        id: 'bomb',
        name: t('nodes', 'bomb.name'),
        icon: 'Skillicon14_02.png',
        description: t('nodes', 'bomb.desc'),
        popupText: t('nodes', 'bomb.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 1,
        baseCost: 50,
        costType: 'data',
        costScaling: 'static',
        parents: ['coverage', 'pulse_expansion'],
        requiresMaxParent: true,
        childIds: ['resonance', 'lore_2'],
        treeX: gridX(3),
        treeY: gridY(0.5),
        effect: function () {
            upgradeDispatcher.recalcBombUses();
        },
    },
    {
        id: 'bomb_2',
        name: t('nodes', 'bomb_2.name'),
        icon: 'Skillicon14_05.png',
        description: t('nodes', 'bomb_2.desc'),
        popupText: t('nodes', 'bomb_2.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 1,
        baseCost: 100,
        costType: 'data',
        costScaling: 'static',
        parents: ['threat_response', 'bypass'],
        childIds: ['peak_traffic'],
        treeX: gridX(-4.5),
        treeY: gridY(2.0),
        effect: function () {
            upgradeDispatcher.recalcBombUses();
        },
    },


    {
        id: 'base_hp_boost',
        name: t('nodes', 'base_hp_boost.name'),
        icon: 'Skillicon14_11.png',
        description: t('nodes', 'base_hp_boost.desc'),
        popupText: t('nodes', 'base_hp_boost.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['security_test_2', 'clock_speed'],
        childIds: ['gateway_discovery'],
        treeX: gridX(-1.0),
        treeY: gridY(8.5),
        effect: function () {
            // Stats recalculated via 'upgradePurchased' â†’ tower._onUpgradePurchased
        },
    },
    {
        id: 'malware_siphon',
        name: t('nodes', 'malware_siphon.name'),
        label: 'HACKING',
        icon: 'Skillicon14_03.png',
        description: t('nodes', 'malware_siphon.desc'),
        popupText: t('nodes', 'malware_siphon.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['instability_mark'],
        childIds: ['root_access'],
        treeX: gridX(1.5),
        treeY: gridY(8.0),
        effect: function () { },
    },

    {
        id: 'threat_response',
        name: t('nodes', 'threat_response.name'),
        icon: 'Skillicon14_27.png',
        description: t('nodes', 'threat_response.desc'),
        popupText: t('nodes', 'threat_response.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        parents: ['emergency_overclock'],
        childIds: ['bomb_2', 'lore_5'],
        treeX: gridX(-3.0),
        treeY: gridY(2.5),
        effect: function () {
            // Logic integrated into gameInit.js listeners
        },
    },
    {
        id: 'placeholder_duo_1',
        isPlaceholder: true,
        parents: ['automated_defense'],
        monitorsDuoTier: 1,
        childIds: ['reveal_map'],

        treeX: gridX(0),
        treeY: gridY(2.125), // Mid-point adjustment (non-clean)
        effect: function () { },
    },
    // â”€â”€ Tier 1 Duo-Box: Lightning Weapon & Shockwave Weapon â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        id: 'lightning_weapon',
        name: t('nodes', 'lightning_weapon.name'),
        icon: 'Skillicon14_33.png',
        description: t('nodes', 'lightning_weapon.desc'),
        popupText: t('nodes', 'lightning_weapon.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        costStep: 0,
        parents: ['automated_defense'],
        childIds: ['lightning_chain', 'lightning_static_charge'],
        isDuoBox: true,
        isLeftDuo: true,
        duoBoxTier: 1,
        shardId: 'lightning_weapon',
        duoSiblingId: 'shockwave_weapon',
        treeX: gridX(0) - DUO_OFFSET, // Symmetric Duo offset (standardized)
        treeY: gridY(2.5),
        effect: function () {
            lightningAttack.unlock();
            shockwaveAttack.lock();
        },
    },
    {
        id: 'shockwave_weapon',
        name: t('nodes', 'shockwave_weapon.name'),
        icon: 'Skillicon14_37.png',
        description: t('nodes', 'shockwave_weapon.desc'),
        popupText: t('nodes', 'shockwave_weapon.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        costStep: 0,
        parents: ['automated_defense'],
        childIds: ['shockwave_amplifier', 'shockwave_seismic_crush'],
        isDuoBox: true,
        duoBoxTier: 1,
        shardId: 'shockwave_weapon',
        duoSiblingId: 'lightning_weapon',
        treeX: gridX(0) + DUO_OFFSET, // Symmetric Duo offset (standardized)
        treeY: gridY(2.5),
        effect: function () {
            shockwaveAttack.unlock();
            lightningAttack.lock();
        },
    },
    {
        id: 'lightning_chain',
        name: t('nodes', 'lightning_chain.name'),
        icon: 'Skillicon14_40.png',
        description: t('nodes', 'lightning_chain.desc'),
        popupText: t('nodes', 'lightning_chain.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 30,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['lightning_weapon'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(-1.5),
        treeY: gridY(2),
        effect: function () {
            upgradeDispatcher.recalcLightningChains();
        },
    },
    {
        id: 'lightning_static_charge',
        name: t('nodes', 'lightning_static_charge.name'),
        icon: 'Skillicon14_10.png',
        description: t('nodes', 'lightning_static_charge.desc'),
        popupText: t('nodes', 'lightning_static_charge.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 3,
        baseCost: 30,
        costType: 'data',
        costScaling: 'linear',
        costStep: 10,
        parents: ['lightning_weapon'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(-1.5),
        treeY: gridY(3),
        effect: function () {
            upgradeDispatcher.recalcLightningDamage();
        },
    },
    {
        id: 'shockwave_amplifier',
        name: t('nodes', 'shockwave_amplifier.name'),
        icon: 'Skillicon14_28.png',
        description: t('nodes', 'shockwave_amplifier.desc'),
        popupText: t('nodes', 'shockwave_amplifier.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 40,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['shockwave_weapon'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(1.5),
        treeY: gridY(2),
        effect: function () {
            upgradeDispatcher.recalcShockwaveStats();
        },
    },
    {
        id: 'shockwave_seismic_crush',
        name: t('nodes', 'shockwave_seismic_crush.name'),
        icon: 'Skillicon14_19.png',
        description: t('nodes', 'shockwave_seismic_crush.desc'),
        popupText: t('nodes', 'shockwave_seismic_crush.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 2,
        baseCost: 40,
        costType: 'data',
        costScaling: 'linear',
        costStep: 20,
        parents: ['shockwave_weapon'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(1.5),
        treeY: gridY(3),
        effect: function () {
            upgradeDispatcher.recalcShockwaveStats();
        },
    },
    {
        id: 'armor',
        name: t('nodes', 'armor.name'),
        icon: 'Skillicon14_18.png',
        description: t('nodes', 'armor.desc'),
        popupText: t('nodes', 'armor.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 1,
        baseCost: 100,
        costType: 'data',
        costScaling: 'linear',
        costStep: 25,
        parents: ['system_redundancy_new'],
        treeX: gridX(-2.5),
        treeY: gridY(4.5),
        childIds: ['regen', 'diagnostic_analytics'],
        effect: function () {
            // Recalculated via 'upgradePurchased' â†’ tower._onUpgradePurchased
        },
    },
    {
        id: 'data_chest_unlock',
        name: t('nodes', 'data_chest_unlock.name'),
        icon: 'Skillicon14_38.png',
        description: t('nodes', 'data_chest_unlock.desc'),
        popupText: t('nodes', 'data_chest_unlock.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        label: 'INSIGHT',
        costType: 'insight',
        costScaling: 'static',
        parents: ['reveal_map'],
        childIds: [],
        treeX: gridX(-0.5),
        treeY: gridY(5),
        effect: function () { },
    },
    {
        id: 'system_redundancy_new',
        name: t('nodes', 'system_redundancy_new.name'),
        icon: 'Skillicon14_18.png',
        description: t('nodes', 'system_redundancy_new.desc'),
        popupText: t('nodes', 'system_redundancy_new.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 1,
        baseCost: 75,
        costType: 'data',
        costScaling: 'static',
        parents: ['reveal_map'],
        childIds: ['emergency_overclock', 'armor'],
        treeX: gridX(-1.5),
        treeY: gridY(4),
        effect: function () { },
    },
    {
        id: 'clock_speed',
        name: t('nodes', 'clock_speed.name'),
        icon: 'Skillicon14_05.png',
        description: t('nodes', 'clock_speed.desc'),
        popupText: t('nodes', 'clock_speed.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 4,
        baseCost: 50,
        costType: 'data',
        costScaling: 'linear',
        costStep: 50,
        costStepScaling: 10,
        parents: ['root_access'],
        childIds: ['base_hp_boost'],
        treeX: gridX(-0.5),
        treeY: gridY(8.5),
        effect: function () {
            // Recalculated via messageBus 'upgradePurchased' â†’ tower._onUpgradePurchased
        },
    },
    {
        id: 'emergency_overclock',
        name: t('nodes', 'emergency_overclock.name'),
        icon: 'Skillicon14_05.png',
        description: t('nodes', 'emergency_overclock.desc'),
        popupText: t('nodes', 'emergency_overclock.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        parents: ['system_redundancy_new'],
        childIds: ['threat_response'],
        treeX: gridX(-2.5),
        treeY: gridY(3.5),
        effect: function () {
            if (typeof tower !== 'undefined') {
                tower.recalcStats();
            }
        },
    },
    {
        id: 'trojan_access',
        name: t('nodes', 'trojan_access.name'),
        label: 'HACKING',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'trojan_access.desc'),
        popupText: t('nodes', 'trojan_access.popup'),
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['packet_sniffing'],
        childIds: ['volatile_payload', 'repeat_exploit'],
        treeX: gridX(2.5),
        treeY: gridY(3.5),
        effect: function () { },
    },
    {
        id: 'volatile_payload',
        name: t('nodes', 'volatile_payload.name'),
        label: 'HACKING',
        icon: 'Skillicon14_10.png',
        description: t('nodes', 'volatile_payload.desc'),
        popupText: t('nodes', 'volatile_payload.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 1,
        baseCost: 2,
        costType: 'coin',
        costScaling: 'static',
        costStep: 0,
        parents: ['trojan_access'],
        childIds: [],
        treeX: gridX(3.5),
        treeY: gridY(4.0),
        effect: function () { },
    },
    {
        id: 'prismatic_array',
        name: t('nodes', 'prismatic_array.name'),
        icon: 'Skillicon14_30.png',
        description: t('nodes', 'prismatic_array.desc'),
        popupText: t('nodes', 'prismatic_array.popup'),
        popupColor: COLORS.UTILITY,
        maxLevel: 5,
        baseCost: 50,
        costType: 'data',
        costScaling: 'linear',
        costStep: 50,
        costStepScaling: 12,
        parents: ['cheat'],
        childIds: [],
        treeX: gridX(-0.5),
        treeY: gridY(-2.5),
        effect: function () {
            // Recalculated via normal gameplay checks
        },
    },
    {
        id: 'resonance',
        name: t('nodes', 'resonance.name'),
        icon: 'Skillicon14_06.png', // Using focus icon for resonance feel or similar
        description: t('nodes', 'resonance.desc'),
        popupText: t('nodes', 'resonance.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 60,
        costType: 'data',
        costScaling: 'static',
        parents: ['bomb'],
        childIds: ['sustaining_siphon', 'crescendo', 'amplitude'],
        treeX: gridX(4),
        treeY: gridY(1),
        effect: function () {
            upgradeDispatcher.recalcResonance();
        },
    },
    {
        id: 'crescendo',
        name: t('nodes', 'crescendo.name'),
        icon: 'Skillicon14_28.png',
        description: t('nodes', 'crescendo.desc'),
        popupText: t('nodes', 'crescendo.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 120,
        costType: 'data',
        costScaling: 'static',
        parents: ['resonance'],
        requiresMaxParent: true,
        childIds: ['hijack'],
        treeX: gridX(4.5),
        treeY: gridY(2),
        effect: function () {
            upgradeDispatcher.recalcResonance();
        },
    },
    {
        id: 'amplitude',
        name: t('nodes', 'amplitude.name'),
        icon: 'Skillicon14_02.png',
        description: t('nodes', 'amplitude.desc'),
        popupText: t('nodes', 'amplitude.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['resonance'],
        requiresMaxParent: true,
        childIds: ['hijack'],
        treeX: gridX(3.5),
        treeY: gridY(2),
        effect: function () {
            upgradeDispatcher.recalcResonance();
        },
    },
    {
        id: 'hijack',
        name: t('nodes', 'hijack.name'),
        icon: 'Skillicon14_03.png',
        description: t('nodes', 'hijack.desc'),
        popupText: t('nodes', 'hijack.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        parents: ['crescendo', 'amplitude'],
        requiresMaxParent: true,
        childIds: ['recursion'],
        treeX: gridX(4.0),
        treeY: gridY(3),
        effect: function () { },
    },
    {
        id: 'recursion',
        name: t('nodes', 'recursion.name'),
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'recursion.desc'),
        popupText: t('nodes', 'recursion.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 3,
        costType: 'coin',
        costScaling: 'static',
        parents: ['hijack'],
        requiresMaxParent: true,
        childIds: [],
        treeX: gridX(4.5),
        treeY: gridY(4),
        effect: function () { },
    },
    {
        id: 'sustaining_siphon',
        name: t('nodes', 'sustaining_siphon.name'),
        icon: 'Skillicon14_11.png',
        description: t('nodes', 'sustaining_siphon.desc'),
        popupText: t('nodes', 'sustaining_siphon.popup'),
        popupColor: COLORS.HEALTH,
        maxLevel: 1,
        baseCost: 2,
        costType: 'coin',
        costScaling: 'static',
        parents: ['resonance'],
        requiresMaxParent: true,
        childIds: [],
        treeX: gridX(5),
        treeY: gridY(1.0),
        effect: function () { },
    },
    {
        id: 'completionist',
        name: t('nodes', 'completionist.name'),
        icon: 'Skillicon14_21.png',
        description: t('nodes', 'completionist.desc'),
        popupText: t('nodes', 'completionist.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        costType: 'insight',
        costScaling: 'static',
        parents: ['cheat'],
        childIds: [],
        treeX: gridX(0.5),
        treeY: gridY(-2.0),
        effect: function () { },
    },
    {
        id: 'bug_report',
        name: t('nodes', 'bug_report.name'),
        icon: 'Skillicon14_06.png',
        description: t('nodes', 'bug_report.desc'),
        popupText: t('nodes', 'bug_report.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        costType: 'insight',
        costScaling: 'static',
        parents: ['integrity'],
        childIds: ['lore_1'],
        treeX: gridX(-2),
        treeY: gridY(0),
        effect: function () { },
    },
    {
        id: 'reveal_map',
        name: t('nodes', 'reveal_map.name'),
        label: t('nodes', 'label.gate'),
        icon: 'Skillicon14_14.png',
        description: t('nodes', 'reveal_map.desc'),
        popupText: t('nodes', 'reveal_map.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 60,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['placeholder_duo_1'],
        childIds: ['system_redundancy_new', 'data_chest_unlock', 'impulse', 'unsecured_wallet'],
        treeX: gridX(0),
        treeY: gridY(4),
        effect: async function () {
            if (typeof cinematicManager !== 'undefined') {
                const endCutscene = await cinematicManager.playCutscene();
                console.log("cutscene");

                const dragGroup = upgradeTree.getDraggableGroup();
                const node = upgradeTree.getNode('reveal_map');
                if (dragGroup && node && node.btn) {
                    const refX = GAME_CONSTANTS.halfWidth * 0.5;
                    const refY = GAME_CONSTANTS.halfHeight;

                    const s0 = dragGroup.getScale();
                    const groupX = dragGroup.x;
                    const groupY = dragGroup.y;

                    // tweenScale with no pivot keeps the group anchor fixed.
                    // After zoom-to-1, a child's world pos = groupAnchor + (currentWorldPos - groupAnchor) / s0
                    const nodeXAfterZoom = groupX + (node.btn.x - groupX) / s0;
                    const nodeYAfterZoom = groupY + (node.btn.y - groupY) / s0;

                    // Pan delta needed to bring that predicted position to the reference point
                    const panX = refX - nodeXAfterZoom;
                    const panY = refY - nodeYAfterZoom;

                    // Zoom out to 1.0 slightly slower than the pan
                    dragGroup.tweenScale(1, {
                        ease: 'Cubic.easeInOut',
                        duration: 1400
                    });

                    dragGroup.tweenBy(panX, panY, {
                        ease: 'Cubic.easeInOut',
                        duration: 1400,
                        onComplete: () => {
                            if (typeof upgradeTree !== 'undefined') {
                                upgradeTree._onSlideRightClicked(upgradeTree.SLIDE_DURATION * 2);
                            }
                            // Wait 1.6s more to fulfill the 3s cutscene requirement (1.4 + 1.6 = 3.0)
                            PhaserScene.time.delayedCall(1600, endCutscene);
                        }
                    });
                } else {
                    PhaserScene.time.delayedCall(3000, endCutscene);
                }
            }
        },
    },
    {
        id: 'test_defenses',
        name: t('nodes', 'test_defenses.name'),
        label: t('nodes', 'label.gate'),
        icon: 'Skillicon14_05.png',
        description: t('nodes', 'test_defenses.desc'),
        popupText: t('nodes', 'test_defenses.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 10,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['magnet'],
        childIds: ['bypass'],
        treeX: gridX(-2),
        treeY: gridY(1),
        effect: function () {
            gameState.upgrades.test_defenses_unlocked = true;
            if (typeof gameHUD !== 'undefined' && gameHUD.refreshTestDefensesButton) {
                gameHUD.refreshTestDefensesButton();
            }
        },
    },
    {
        id: 'bypass',
        name: t('nodes', 'bypass.name'),
        icon: 'Skillicon14_07.png',
        description: t('nodes', 'bypass.desc'),
        popupText: t('nodes', 'bypass.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['test_defenses'],
        childIds: ['bomb_2'],
        treeX: gridX(-3.5),
        treeY: gridY(0.5),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(150);
            }
        },
    },
    {
        id: 'data_compression',
        name: t('nodes', 'data_compression.name'),
        icon: 'Skillicon14_20.png',
        description: t('nodes', 'data_compression.desc'),
        popupText: t('nodes', 'data_compression.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 2,
        baseCost: 1,
        label: 'INSIGHT',
        costType: 'insight',
        costScaling: 'static',
        costStep: 0,
        parents: ['diagnostic_analytics'],
        childIds: [],
        treeX: gridX(-4.5),
        treeY: gridY(5.0),
        effect: function () { },
    },
    {
        id: 'two_step_auth',
        name: t('nodes', 'two_step_auth.name'),
        icon: 'Skillicon14_10.png',
        description: t('nodes', 'two_step_auth.desc'),
        popupText: t('nodes', 'two_step_auth.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        label: '"UTILITY"',
        costType: 'insight',
        costScaling: 'static',
        parents: ['cheat'],
        childIds: [],
        tooltipExtraWidth: 40,
        treeX: gridX(1.5),
        treeY: gridY(-2.0),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(100);
            }
        },
    },
    {
        id: 'packet_sniffing',
        name: t('nodes', 'packet_sniffing.name'),
        icon: 'Skillicon14_01.png',
        description: t('nodes', 'packet_sniffing.desc'),
        popupText: t('nodes', 'packet_sniffing.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        label: 'INSIGHT',
        costType: 'insight',
        costScaling: 'static',
        parents: ['coverage'],
        childIds: ['trojan_access'],
        treeX: gridX(2.5),
        treeY: gridY(2),
        effect: function () {
            upgradeDispatcher.recalcPacketSniffing();
        },
    },

    {
        id: 'junk_data_2',
        name: t('nodes', 'junk_data_2.name'),
        label: t('nodes', 'label.plus_data'),
        icon: 'Skillicon14_12.png',
        description: t('nodes', 'junk_data_2.desc'),
        popupText: t('nodes', 'junk_data_2.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 10,
        baseCost: 2,
        label: t('nodes', 'label.plus_data'),
        costType: 'data',
        costScaling: 'static',
        requiresMaxParent: true,
        parents: ['peak_traffic'],
        childIds: [],
        treeX: gridX(-4.5),
        treeY: gridY(1.0),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(10);
            }
        },
    },
    {
        id: 'repeat_exploit',
        name: t('nodes', 'repeat_exploit.name'),
        label: 'HACKING',
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'repeat_exploit.desc'),
        popupText: t('nodes', 'repeat_exploit.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 75,
        costType: 'data',
        costScaling: 'static',
        parents: ['trojan_access', 'impulse'],
        childIds: ['placeholder_duo_2', 'manual_protocol', 'broadcast_protocol'],
        treeX: gridX(2.5),
        treeY: gridY(4.5),
        effect: function () {
            upgradeDispatcher.recalcRepeatExploit();
            if (typeof upgradeTree !== 'undefined') upgradeTree.unlockNode('trojan_access');
        },
    },
    {
        id: 'unsecured_wallet',
        name: t('nodes', 'unsecured_wallet.name'),
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'unsecured_wallet.desc'),
        popupText: t('nodes', 'unsecured_wallet.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 1,
        label: 'INSIGHT',
        costType: 'insight',
        costScaling: 'static',
        parents: ['reveal_map'],
        childIds: [],
        tooltipExtraWidth: 140,
        treeX: gridX(0.5),
        treeY: gridY(5),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                // Internally give 5 coins, which displays as 0.5 (0.1x scale)
                resourceManager.addCoin(5);
            }
        },
    },

    {
        id: 'impulse',
        name: t('nodes', 'impulse.name'),
        icon: 'Skillicon14_02.png',
        description: t('nodes', 'impulse.desc'),
        popupText: t('nodes', 'impulse.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 40,
        costType: 'data',
        costScaling: 'static',
        parents: ['reveal_map'],
        childIds: ['repeat_exploit'],
        treeX: gridX(1.5),
        treeY: gridY(4),
        effect: function () {
            upgradeDispatcher.recalcPulseDamage();
            if (typeof upgradeTree !== 'undefined') upgradeTree.unlockNode('trojan_access');
        },
    },

    {
        id: 'root_access',
        name: t('nodes', 'root_access.name'),
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'root_access.desc'),
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['malware_siphon', 'shell_access'],
        childIds: ['clock_speed'],
        treeX: gridX(0.5),
        treeY: gridY(8.0),
        effect: function () { },
    },
    {
        id: 'placeholder_duo_3',
        isPlaceholder: true,
        parents: ['diagnostic_analytics'],
        monitorsDuoTier: 3,
        childIds: ['security_test_3'],
        treeX: gridX(-3.5),
        treeY: gridY(6.5),
        effect: function () { },
    },
    {
        id: 'laser',
        name: t('nodes', 'laser.name'),
        icon: 'Skillicon14_06.png',
        description: t('nodes', 'laser.desc'),
        popupText: t('nodes', 'laser.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        parents: ['diagnostic_analytics'],
        childIds: ['laser_aperture', 'laser_disintegration'],
        isDuoBox: true,
        isLeftDuo: true,
        duoBoxTier: 3,
        shardId: 'laser',
        duoSiblingId: 'artillery',
        treeX: gridX(-3.5) - DUO_OFFSET,
        treeY: gridY(6.5),
        effect: function () {
            if (typeof laserAttack !== 'undefined') laserAttack.unlock();
            artilleryAttack.lock();
        },
    },
    {
        id: 'artillery',
        name: t('nodes', 'artillery.name'),
        icon: 'Skillicon14_11.png',
        description: t('nodes', 'artillery.desc'),
        popupText: t('nodes', 'artillery.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        duoSiblingId: 'laser',
        treeX: gridX(-3.5) + DUO_OFFSET,
        treeY: gridY(6.5),
        parents: ['diagnostic_analytics'],
        childIds: ['artillery_shells', 'artillery_first_strike'],
        isDuoBox: true,
        duoBoxTier: 3,
        shardId: 'artillery',
        effect: function () {
            artilleryAttack.unlock();
            if (typeof laserAttack !== 'undefined') laserAttack.lock();
        },
    },
    {
        id: 'laser_aperture',
        name: t('nodes', 'laser_aperture.name'),
        icon: 'Skillicon14_22.png',
        description: t('nodes', 'laser_aperture.desc'),
        popupText: t('nodes', 'laser_aperture.popup'),
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        parents: ['laser'],
        childIds: ['laser_twin_beams'],
        isDuoChild: true,
        treeX: gridX(-5.0),
        treeY: gridY(6.0),
        effect: function () {
            upgradeDispatcher.recalcLaser();
        },
    },
    {
        id: 'laser_disintegration',
        name: t('nodes', 'laser_disintegration.name'),
        icon: 'Skillicon14_26.png',
        description: t('nodes', 'laser_disintegration.desc'),
        popupText: t('nodes', 'laser_disintegration.popup'),
        maxLevel: 3,
        baseCost: 50,
        costType: 'data',
        costScaling: 'linear',
        costStep: 50,
        parents: ['laser'],
        childIds: ['laser_twin_beams'],
        isDuoChild: true,
        treeX: gridX(-5.0),
        treeY: gridY(7.0),
        effect: function () {
            upgradeDispatcher.recalcLaser();
        },
    },
    {
        id: 'laser_twin_beams',
        name: t('nodes', 'laser_twin_beams.name'),
        icon: 'Skillicon14_30.png',
        description: t('nodes', 'laser_twin_beams.desc'),
        popupText: t('nodes', 'laser_twin_beams.popup'),
        maxLevel: 1,
        baseCost: 300,
        costType: 'data',
        costScaling: 'static',
        parents: ['laser_aperture', 'laser_disintegration'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(-6.0),
        treeY: gridY(6.5),
        effect: function () {
            upgradeDispatcher.recalcLaser();
        },
    },
    {
        id: 'artillery_volley',
        name: t('nodes', 'artillery_volley.name'),
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'artillery_volley.desc'),
        popupText: t('nodes', 'artillery_volley.popup'),
        maxLevel: 1,
        baseCost: 200,
        costType: 'data',
        costScaling: 'static',
        parents: ['artillery_shells'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(-1.0),
        treeY: gridY(7.0),
        requiresMaxParent: true,
        effect: function () { upgradeDispatcher.recalcArtillery(); },
    },

    {
        id: 'artillery_shells',
        name: t('nodes', 'artillery_shells.name'),
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'artillery_shells.desc'),
        popupText: t('nodes', 'artillery_shells.popup'),
        maxLevel: 1,
        baseCost: 50,
        costType: 'data',
        costScaling: 'linear',
        costStep: 0,
        parents: ['artillery'],
        childIds: ['artillery_volley'],
        isDuoChild: true,
        treeX: gridX(-2.0),
        treeY: gridY(7.0),
        effect: function () { upgradeDispatcher.recalcArtillery(); },
    },
    {
        id: 'artillery_first_strike',
        name: t('nodes', 'artillery_first_strike.name'),
        icon: 'Skillicon14_31.png',
        description: t('nodes', 'artillery_first_strike.desc'),
        popupText: t('nodes', 'artillery_first_strike.popup'),
        maxLevel: 3,
        baseCost: 75,
        costType: 'data',
        costScaling: 'linear',
        costStep: 0,
        parents: ['artillery'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(-2.0),
        treeY: gridY(6.0),
        effect: function () { upgradeDispatcher.recalcArtillery(); },
    },
    {
        id: 'shell_access',
        name: t('nodes', 'shell_access.name'),
        icon: 'Skillicon14_34.png',
        description: t('nodes', 'shell_access.desc'),
        maxLevel: 1,
        baseCost: 250,
        costType: 'data',
        costScaling: 'static',
        parents: ['security_test_2'],
        childIds: ['root_access'],
        treeX: gridX(0.5),
        treeY: gridY(7.5),
        popupText: t('nodes', 'shell_access.popup'),
        popupColor: COLORS.COMBAT,
        effect: function () {
            // Recalculated by tower.js listener
        },
    },

    {
        id: 'unsecured_files',
        name: t('nodes', 'unsecured_files.name'),
        icon: 'Skillicon14_08.png',
        description: t('nodes', 'unsecured_files.desc'),
        popupText: '+15 DATA',
        popupColor: COLORS.RESOURCE,
        maxLevel: 10,
        baseCost: 1,
        label: t('nodes', 'label.plus_data'),
        costType: 'data',
        costScaling: 'static',
        parents: ['cheat'],
        childIds: [],
        treeX: gridX(-1.5),
        treeY: gridY(-1.5),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(15);
            }
        },
    },
    {
        id: 'zero_day_exploit',
        name: t('nodes', 'zero_day_exploit.name'),
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'zero_day_exploit.desc'),
        popupText: t('nodes', 'zero_day_exploit.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 50,
        label: "HACKING",
        costType: 'data',
        costScaling: 'static',
        parents: ['cheat'],
        childIds: [],
        treeX: gridX(-0.5),
        treeY: gridY(-2.5),
        effect: function () { },
    },
    {
        id: 'placeholder_duo_2',
        isPlaceholder: true,
        parents: ['repeat_exploit'],
        monitorsDuoTier: 2,
        childIds: ['manual_protocol', 'broadcast_protocol', 'instability_mark'],
        treeX: gridX(2.5),
        treeY: gridY(6.0),
        effect: function () { },
    },
    {
        id: 'security_test_2',
        name: t('nodes', 'security_test_2.name'),
        label: t('nodes', 'label.gate'),
        icon: 'Skillicon14_38.png',
        description: t('nodes', 'security_test_2.desc'),
        maxLevel: 1,
        baseCost: 600,
        costType: 'data',
        costScaling: 'static',
        parents: [],
        childIds: ['base_hp_boost', 'shell_access', 'gateway_discovery'],
        treeX: gridX(0),
        treeY: gridY(7),
        tooltipExtraWidth: 25,
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(500);
            }
        },
    },
    {
        id: 'instability_mark',
        name: t('nodes', 'instability_mark.name'),
        icon: 'Skillicon14_09.png',
        description: t('nodes', 'instability_mark.desc'),
        popupText: t('nodes', 'instability_mark.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 150,
        costType: 'data',
        costScaling: 'static',
        parents: ['placeholder_duo_2'],
        childIds: ['malware_siphon', 'core_synergy'],
        treeX: gridX(2.5),
        treeY: gridY(7.5),
        effect: function () {
            upgradeDispatcher.recalcPulseDamage();
        },
    },
    {
        id: 'manual_protocol',
        name: t('nodes', 'manual_protocol.name'),
        icon: 'Skillicon14_34.png',
        description: t('nodes', 'manual_protocol.desc'),
        popupText: t('nodes', 'manual_protocol.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        parents: ['repeat_exploit'],
        childIds: ['manual_pulse_child_1'],
        isDuoBox: true,
        duoBoxTier: 2,
        shardId: 'manual_protocol',
        duoSiblingId: 'broadcast_protocol',
        treeX: gridX(2.5) + DUO_OFFSET, // Symmetric Duo offset (standardized)
        treeY: gridY(6),
        effect: function () {
            upgradeDispatcher.recalcPulseMode();
            upgradeDispatcher.recalcPulseSize();
        },
    },
    {
        id: 'broadcast_protocol',
        name: t('nodes', 'broadcast_protocol.name'),
        icon: 'Skillicon14_28.png',
        description: t('nodes', 'broadcast_protocol.desc'),
        popupText: t('nodes', 'broadcast_protocol.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 1,
        baseCost: 1,
        costType: 'shard',
        costScaling: 'static',
        parents: ['repeat_exploit'],
        childIds: ['area_saturation', 'aftershock', 'colossal_cursor'],
        isDuoBox: true,
        isLeftDuo: true,
        duoBoxTier: 2,
        shardId: 'broadcast_protocol',
        duoSiblingId: 'manual_protocol',
        treeX: gridX(2.5) - DUO_OFFSET, // Symmetric Duo offset (standardized)
        treeY: gridY(6),
        effect: function () {
            upgradeDispatcher.recalcPulseSize();
            upgradeDispatcher.recalcPulseMode();
        },
    },
    {
        id: 'manual_pulse_child_1',
        name: t('nodes', 'manual_pulse_child_1.name'),
        icon: 'Skillicon14_33.png',
        description: t('nodes', 'manual_pulse_child_1.desc'),
        popupText: t('nodes', 'manual_pulse_child_1.popup'),
        maxLevel: 3,
        baseCost: 40,
        costType: 'data',
        costScaling: 'linear',
        costStep: 20,
        parents: ['manual_protocol'],
        childIds: ['manual_pulse_child_1_1', 'manual_pulse_child_1_2'],
        isDuoChild: true,
        treeX: gridX(4.0),
        treeY: gridY(6),
        effect: function () {
            upgradeDispatcher.recalcPulseCharges();
        },
    },
    {
        id: 'manual_pulse_child_1_1',
        name: t('nodes', 'manual_pulse_child_1_1.name'),
        icon: 'Skillicon14_25.png',
        description: t('nodes', 'manual_pulse_child_1_1.desc'),
        popupText: t('nodes', 'manual_pulse_child_1_1.popup'),
        maxLevel: 2,
        baseCost: 50,
        costType: 'data',
        costScaling: 'linear',
        costStep: 50,
        parents: ['manual_pulse_child_1'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(5.0),
        treeY: gridY(6.5),
        effect: function () {
            upgradeDispatcher.recalcPulseDamage();
        },
    },
    {
        id: 'manual_pulse_child_1_2',
        name: t('nodes', 'manual_pulse_child_1_2.name'),
        icon: 'Skillicon14_17.png',
        description: t('nodes', 'manual_pulse_child_1_2.desc'),
        popupText: t('nodes', 'manual_pulse_child_1_2.popup'),
        maxLevel: 1,
        baseCost: 75,
        costType: 'data',
        costScaling: 'static',
        parents: ['manual_pulse_child_1'],
        requiresMaxParent: true,
        childIds: [],
        isDuoChild: true,
        treeX: gridX(5.0),
        treeY: gridY(5.5),
        effect: function () {
            upgradeDispatcher.recalcPulseReload();
        },
    },
    {
        id: 'area_saturation',
        name: t('nodes', 'area_saturation.name'),
        icon: 'Skillicon14_22.png',
        description: t('nodes', 'area_saturation.desc'),
        popupText: t('nodes', 'area_saturation.popup'),
        maxLevel: 1,
        baseCost: 50,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['broadcast_protocol'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(1.5),
        treeY: gridY(7),
        effect: function () {
            upgradeDispatcher.recalcPulseDamage();
        },
    },
    {
        id: 'aftershock',
        name: t('nodes', 'aftershock.name'),
        icon: 'Skillicon14_21.png',
        description: t('nodes', 'aftershock.desc'),
        popupText: t('nodes', 'aftershock.popup'),
        popupColor: COLORS.DAMAGE,
        maxLevel: 2,
        baseCost: 40,
        costType: 'data',
        costScaling: 'linear',
        costStep: 0,
        parents: ['broadcast_protocol'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(1.5),
        treeY: gridY(5),
        effect: function () {
            upgradeDispatcher.recalcAftershock();
        },
    },
    {
        id: 'colossal_cursor',
        name: t('nodes', 'colossal_cursor.name'),
        icon: 'Skillicon14_14.png',
        description: t('nodes', 'colossal_cursor.desc'),
        popupText: t('nodes', 'colossal_cursor.popup'),
        popupColor: COLORS.UPGRADE,
        maxLevel: 1,
        baseCost: 75,
        costType: 'data',
        costScaling: 'static',
        parents: ['broadcast_protocol'],
        childIds: [],
        isDuoChild: true,
        treeX: gridX(1.0),
        treeY: gridY(6),
        requiresMaxParent: false,
        effect: function () {
            upgradeDispatcher.recalcPulseSize();
        },
    },
    {
        id: 'gateway_discovery',
        name: t('nodes', 'gateway_discovery.name'),
        icon: 'Skillicon14_38.png',
        description: t('nodes', 'gateway_discovery.desc'),
        popupText: t('nodes', 'gateway_discovery.popup'),
        maxLevel: 1,
        baseCost: 10,
        costType: 'data',
        parents: ['security_test_2', 'base_hp_boost'],
        childIds: ['physical_anchor', 'coin_mine_unlock'],
        treeX: gridX(0.0),
        treeY: gridY(8.0),
        effect: function () { },
    },
    {
        id: 'security_test_3',
        name: t('nodes', 'security_test_3.name'),
        label: t('nodes', 'label.gate'),
        icon: 'Skillicon14_38.png',
        description: t('nodes', 'security_test_3.desc'),
        popupText: t('nodes', 'security_test_3.popup'),
        maxLevel: 1,
        baseCost: 1000,
        costType: 'data',
        costScaling: 'static',
        parents: ['placeholder_duo_3'],
        childIds: [],
        treeX: gridX(-3.5),
        treeY: gridY(8.0),
        effect: function () {
            if (typeof resourceManager !== 'undefined') {
                resourceManager.addData(1000);
            }
        },
    },
    {
        id: 'coin_mine_unlock',
        name: t('nodes', 'coin_mine_unlock.name'),
        icon: 'Skillicon14_35.png',
        description: t('nodes', 'coin_mine_unlock.desc'),
        popupText: t('nodes', 'coin_mine_unlock.popup'),
        popupColor: COLORS.RESOURCE,
        maxLevel: 1,
        baseCost: 0,
        costType: 'data',
        costScaling: 'static',
        costStep: 0,
        parents: ['gateway_discovery'],
        childIds: [],
        treeX: gridX(-1.5),
        treeY: gridY(8.0),
        effect: function () {
            if (typeof upgradeTree !== 'undefined') {
                upgradeTree._showCoinMineButton();
            }
        },
    },
    {
        id: 'physical_anchor',
        name: t('nodes', 'physical_anchor.name'),
        icon: 'Skillicon14_16.png',
        description: t('nodes', 'physical_anchor.desc'),
        maxLevel: 1,
        baseCost: 1,
        costType: 'coin',
        costScaling: 'static',
        parents: ['gateway_discovery'],
        childIds: [],
        treeX: gridX(-1.0),
        treeY: gridY(7.0),
        popupText: t('nodes', 'physical_anchor.popup'),
        popupColor: COLORS.UTILITY,
        effect: function () {
            // Stats recalculated by tower.js listener
        },
    },
    {
        id: 'core_synergy',
        name: t('nodes', 'core_synergy.name'),
        icon: 'Skillicon14_26.png',
        description: t('nodes', 'core_synergy.desc'),
        popupText: t('nodes', 'core_synergy.popup'),
        popupColor: COLORS.COMBAT,
        maxLevel: 3,
        baseCost: 200,
        costType: 'data',
        costScaling: 'linear',
        costStep: 100,
        parents: ['instability_mark'],
        childIds: [],
        treeX: gridX(3.5),
        treeY: gridY(8.0),
        effect: function () { },
    },
];
