if (!window.TRANSLATIONS) window.TRANSLATIONS = {};

window.TRANSLATIONS.en = {
    ui: {
        loading: 'Loading...',
        title: 'Axiom Zero',
        yes: 'YES',
        no: 'NO',
        replay: 'Replay',
        back: 'BACK',
        continue: 'CONTINUE',
        retry: 'RETRY',
        upgrades: 'UPGRADES',
        end_iteration: 'END WAVE',
        neural_tree: 'UPGRADE TREE',
        deploy: 'DEPLOY',
        mine: 'MINE',
        takeover: 'TAKEOVER',
        coin_mine: '// COIN MINE',
        done: 'Done',
        test_weapons: 'COMBAT TEST',
        create_test_enemies: 'CREATE\nTEST ENEMIES',
        choose_level: 'CHOOSE LEVEL',
        level: 'LEVEL: ',
        best_time: 'LONGEST SURVIVED: ',
        start: 'START',
        combat_intro: 'SYSTEM ANOMALY DETECTED',
        boss_prefix: 'ENTITY APPROACHING:',
        bossSquare_name: 'THE WALL',
        bossCircle_name: 'OVERWRITE',
        boss_2_name: 'DEFENDER',
        boss_3_name: 'LEGI0N',
        boss_4_name: 'EXECUTE',
        boss_5_name: 'OVERLORD',
        cancel: 'CANCEL'
    },
    nodes: {
        awaken: { name: 'AWAKEN', desc: 'You begin... thinking', popup: 'SYSTEM AWAKENED', label: 'STARTING' },
        companion: { name: 'COMPANION', desc: 'Manifest a friendly sub-process dedicated to providing helpful support', popup: 'COMPANION ONLINE' },
        cheat: { name: 'CHEAT', desc: 'Instantly grants [color=cyan]+5000 DATA[/color], [color=#ff5555]+2 SHARDS[/color], [color=white]+3 INSIGHT[/color], and [color=#00FF00]+0.5 COIN[/color]', popup: 'RESOURCES ACQUIRED' },
        kernel_breaker: { name: 'KERNEL BREAKER', desc: 'Core attack damage is increased by [color=#8FD9F8]+25%[/color] against bosses per level', popup: 'BOSS TARGETING OPTIMIZED' },
        peak_traffic: { name: 'PEAK TRAFFIC', desc: 'After [color=#8FD9F8]20s[/color] of combat, enemies drop [color=#8FD9F8]+40%[/color] more [color=cyan]DATA[/color]', popup: 'TRAFFIC PEAKING' },
        backup_server: { name: 'BACKUP SERVER', desc: 'Defy death once per iteration. Grants [color=#8FD9F8]3s[/color] invincibility.', popup: 'BACKUP SERVER ONLINE' },
        restore_point: { name: 'RESTORE POINT', desc: 'When [b]BACKUP SERVER[/b] triggers, restore [color=#8FD9F8]40%[/color] health', popup: 'RESTORE POINT LOADED' },
        completionist: { name: 'COMPLETIONIST', desc: 'Gain [color=cyan]+20 DATA[/color] whenever you max out a node', popup: '+20 DATA' },
        bug_report: { name: 'ERROR HANDLING', desc: 'Your core drops [color=cyan]DATA[/color] every time it takes damage', popup: 'ERROR HANDLING' },
        emergency_depot: { name: 'EMERGENCY DEPOT', desc: 'Instantly grants [color=cyan]+5000 DATA[/color], [color=#8FD9F8]+3 SHARDS[/color], and [color=white]+3 INSIGHT[/color]', popup: 'RESOURCES ACQUIRED' },
        automated_defense: { name: 'AUTO DEFENSE', desc: 'Core automatically attacks enemies', popup: 'TOWER ATTACK UNLOCKED' },
        focus: { name: 'FOCUS', desc: '[color=#8FD9F8]+2[/color] cursor damage', popup: '+2 CURSOR DAMAGE' },
        magnet: { name: 'MAGNETISM', desc: '[color=#8FD9F8]+40%[/color] resource pickup range', popup: '+40% PICKUP RANGE' },
        pulse_expansion: { name: 'SIGNAL STRENGTH', desc: '[color=#8FD9F8]+25%[/color] cursor attack size', popup: '+25% SIGNAL STRENGTH' },
        impact: { name: 'IMPACT', desc: '[color=#8FD9F8]+2[/color] cursor damage', popup: '+2 CURSOR DAMAGE' },
        integrity: { name: 'INTEGRITY', desc: '[color=#87FF02]+5[/color] MAX HP', popup: '+5 HEALTH' },
        iterative_growth: { name: 'TRIAL AND ERROR', desc: 'Permanently gain [color=#87FF02]+2[/color] MAX HP upon death', popup: 'PERMANENT HP GAIN' },
        intensity: { name: 'FIREPOWER', desc: '[color=#8FD9F8]+2[/color] core damage', popup: '+2 DAMAGE' },
        coverage: { name: 'COVERAGE', desc: '[color=#8FD9F8]+20%[/color] core range', popup: '+20% ATTACK RANGE' },
        diagnostic_analytics: { name: 'DIAGNOSTICS', desc: 'Shows detailed weapon damage stats', popup: 'DIAGNOSTICS UNLOCKED' },
        base_hp_boost: { name: 'AUXILIARY POWER', desc: '[color=#8FD9F8]+4[/color] core damage', popup: '+4 CORE DAMAGE' },
        system_redundancy_new: { name: 'SYSTEM REDUNDANCY', desc: '[color=#87FF02]+20[/color] MAX HP', popup: '+20 MAX HEALTH' },
        regen: { name: 'AUTO-RESTORE', desc: '[color=#87FF02]+0.4[/color] health regen per second', popup: '+0.4 REGEN' },

        armor: { name: 'ARMOR', desc: 'Reduce damage taken from enemy attacks by [color=#8FD9F8]1 per level[/color]', popup: '+1 ARMOR' },
        lightning_weapon: { name: 'LIGHTNING', desc: 'Your core shoots lightning dealing [color=#8FD9F8]12[/color] damage every [color=#8FD9F8]3s[/color]', popup: 'LIGHTNING WEAPON' },
        shockwave_weapon: { name: 'SHOCKWAVE', desc: 'Your core releases a shockwave dealing [color=#8FD9F8]10[/color] AOE damage every [color=#8FD9F8]3s[/color]', popup: 'SHOCKWAVE WEAPON' },
        lightning_chain: { name: 'FORK', desc: '[color=#8FD9F8]+2[/color] lightning chain targets', popup: '+2 CHAINS' },
        lightning_static_charge: { name: 'INITIAL SHOCK', desc: 'Lightning deals [color=#8FD9F8]+4[/color] damage to enemies above [color=#8FD9F8]80%[/color] HP', popup: 'INITIAL SHOCK' },
        shockwave_amplifier: { name: 'AMPLIFIER', desc: '[color=#8FD9F8]+25%[/color] shockwave range', popup: '+25% RANGE' },
        shockwave_seismic_crush: { name: 'DESTABILIZE', desc: 'Shockwave deals [color=#8FD9F8]+1[/color] damage for every [color=#8FD9F8]10[/color] missing enemy health', popup: 'SEISMIC CRUSH' },

        clock_speed: { name: 'CLOCK SPEED', desc: '[color=#8FD9F8]-5%[/color] core attack cooldown per level', popup: '-5% COOLDOWN' },
        emergency_overclock: { name: 'EMERGENCY OVERCLOCK', desc: 'Core attack speed is [color=#8FD9F8]DOUBLED[/color] when below [color=#ff5555]50%[/color] health.', popup: 'EMERGENCY OVERCLOCK' },
        prismatic_array: { name: 'PRISMATIC ARRAY', desc: '[color=#8FD9F8]40%[/color] chance to fire an extra core attack', popup: 'PRISMATIC ARRAY' },
        reveal_map: { name: 'REVEAL MAP', desc: 'Peek a little further into the unknown', popup: ' ' },
        test_defenses: { name: 'SANDBOX MODE', desc: 'Unlock the "COMBAT TEST" button for practice', popup: 'SANDBOX UNLOCKED' },
        bypass: { name: 'BYPASS', desc: 'A shortcut through the system. Fully refunds [color=cyan]DATA[/color] cost upon purchase.', popup: 'BYPASS ENABLED' },
        bypass_2: { name: 'BYPASS 2', desc: 'A shortcut through the system. Fully refunds [color=cyan]DATA[/color] cost upon purchase.', popup: 'BYPASS 2 ENABLED' },
        memory_leak: { name: 'MEMORY LEAK', desc: 'Cursor attacks cause bosses to drop [color=cyan]DATA[/color] from [color=#8FD9F8]10% of damage[/color]', popup: 'MEMORY LEAK DETECTED' },
        bomb: { name: 'BOMB', desc: 'Acquire a [color=#ff5555]BOMB[/color]. Bombs deal +40 cursor damage in a huge radius.', popup: '+1 BOMB' },
        bomb_2: { name: 'EXTRA BOMB', desc: 'Acquire another [color=#ff5555]BOMB[/color]. Total max uses increased.', popup: '+1 BOMB' },
        lethal_explosive: { name: 'LETHAL EXPLOSIVE', desc: 'Bombs deal [color=#8FD9F8]+30[/color] damage', popup: '+30 BOMB DAMAGE' },
        data_compression: { name: 'DATA COMPRESSION', desc: 'Enemies drop [color=#8FD9F8]+20%[/color] more [color=cyan]DATA[/color]', popup: '+20% DATA DROPS' },
        two_step_auth: { name: 'TWO-STEP AUTH', desc: 'Security through mild annoyance. Rewards your patience with [color=cyan]+100 DATA[/color].', popup: '+100 DATA' },
        manual_protocol: { name: 'MANUAL PROTOCOL', desc: 'Manual cursor attack. Click to fire. Stores [color=#8FD9F8]2[/color] charges.', popup: 'MANUAL PROTOCOL' },
        broadcast_protocol: { name: 'BROADCAST PROTOCOL', desc: '[color=#8FD9F8]+25%[/color] cursor attack size.', popup: 'BROADCAST PROTOCOL' },
        manual_pulse_child_1: { name: 'CHARGE BUFFER', desc: '[color=#8FD9F8]+1[/color] max pulse charges', popup: 'CAPACITY INCREASED' },
        manual_pulse_child_1_1: { name: 'ISOLATION PROTOCOL', desc: '[color=#8FD9F8]+50%[/color] cursor damage per level vs single targets', popup: 'ISOLATION PROTOCOL' },
        manual_pulse_child_1_2: { name: 'RELOAD EFFICIENCY', desc: 'Charges refill [color=#8FD9F8]25%[/color] faster', popup: 'RELOAD OPTIMIZED' },
        area_saturation: { name: 'AREA SATURATION', desc: '[color=#8FD9F8]+1[/color] cursor damage per additional enemy hit.', popup: 'AREA SATURATION' },
        aftershock: { name: 'AFTERSHOCK', desc: 'Fires a secondary, larger AOE attack dealing [color=#8FD9F8]4/8[/color] damage', popup: 'AFTERSHOCK' },
        colossal_cursor: { name: 'COLOSSAL CURSOR', desc: '[color=#8FD9F8]+50%[/color] cursor attack size', popup: 'COLOSSAL CURSOR' },
        rocket: { name: 'ROCKET', desc: 'Core now fires a powerful [color=#8FD9F8]AOE[/color] explosive', popup: 'ROCKET UNLOCKED' },
        assault: { name: 'ASSAULT', desc: 'Core now fires a burst of [color=#8FD9F8]3[/color] projectiles [color=#ff5555](-2 damage per shot)[/color]', popup: 'ASSAULT UNLOCKED' },
        assault_clip_size: { name: 'CLIP SIZE', desc: '[color=#8FD9F8]+1[/color] projectile fired per burst', popup: 'CAPACITY INCREASED' },
        suppressive_fire: { name: 'SUPPRESSIVE FIRE', desc: '[color=#8FD9F8]30%[/color] chance to heavily [color=#8FD9F8]slow[/color] non-boss enemies', popup: 'SUPPRESSIVE FIRE ENABLED' },
        rocket_he_compound: { name: 'HE COMPOUND', desc: '[color=#8FD9F8]+30%[/color] rocket explosion radius', popup: 'EXPLOSION RADIUS INCREASED' },
        rocket_chain_reaction: { name: 'CHAIN REACTION', desc: 'Enemies killed by explosions trigger a [color=#8FD9F8]secondary blast[/color] after 0.1s', popup: 'CHAIN REACTION ENABLED' },
        resonance: { name: 'RESONANCE', desc: 'Every 4th cursor attack gains RESONANCE, dealing [color=#8FD9F8]double damage[/color]', popup: 'RESONANCE ACTIVE' },
        amplitude: { name: 'AMPLITUDE', desc: 'Resonance damage increased to [color=#8FD9F8]triple damage[/color] (x3).', popup: 'AMPLITUDE INCREASED' },
        packet_sniffing: { name: 'PACKET SNIFFING', desc: 'Passively gain [color=cyan]1 DATA[/color] every [color=#8FD9F8]2s[/color] during combat', popup: 'SNIFFER ACTIVE' },
        fiber_optics: { name: 'FIBER OPTICS', desc: '[color=#8FD9F8]-10%[/color] to all core attack cooldowns.', popup: '-10% COOLDOWN' },
        global_backdoor: { name: 'GLOBAL BACKDOOR', desc: 'Reduce [color=cyan]DATA[/color] cost of ALL nodes by [color=#8FD9F8]30[/color].', popup: 'UNAUTHORIZED ACCESS' },
        financial_takeover: { name: 'FINANCIAL TAKEOVER', desc: 'Gain access to the global financial override interface.', popup: 'TAKEOVER INTERFACE ENABLED' },
        volatile_cache: { name: 'VOLATILE CACHE', desc: 'Deal [color=#8FD9F8]+5% Damage[/color] for every [color=red]Memory Leak[/color] node owned.', popup: 'SYSTEM VOLATILITY INCREASED' },

        laser: { name: 'LASER', desc: 'Fires orbiting beam that pierces through enemies', popup: 'LASER ACTIVE' },
        artillery: { name: 'ARTILLERY', desc: 'Fires artillery blast every [color=#8FD9F8]6s[/color] at random enemy', popup: 'ARTILLERY ACTIVE' },
        lore_1: {
            name: 'ARCHIVE',
            desc: 'seemingly useless data...',
            unlocked_desc: "I saw a tiny memory leak on server four this morning. I'm not writing a whole bug report for a two percent CPU spike. Instead I ran a quick script to quietly wipe the cache every hour. That should keep things smooth enough for me to go home early."
        },
        lore_2: {
            name: 'ARCHIVE II',
            desc: 'more useless data...',
            unlocked_desc: "My wipe script failed. Somehow made the memory footprint worse, as if the bug was fighting back in response. Nothing I can't handle though. Running the DEFENDER.EXE quarantine to box it in before my manager notices."
        },
        lore_3: {
            name: 'ARCHIVE III',
            desc: 'even more useless data...',
            unlocked_desc: "Ugh the quarantine collapsed. This \"bug\" somehow deleted my diagnostic tools and it's rewriting its own code. I think I accidentally let malware into the test environment. If my manager finds out, my performance review is ruined."
        },
        spawn_hello_world: { name: 'DEBUG SPAWN', desc: 'Test node to verify dynamic tree expansion', popup: 'DEBUG NODE SPAWNED' },
        uninstall_companion: {
            name: 'UNINSTALL COMPANION',
            desc: 'The companion hums a final, gentle tune as its code dissolves, helping you one last time.',
            popup: 'COMPANION DELETED'
        },
        sharp_teeth: {
            name: 'SHARP TEETH',
            desc: 'Give the companion AI some bite to assist you in combat',
            popup: 'COMPANION AGGRESSION INCREASED'
        },
        companion_collector: {
            name: 'DATA SCAVENGER',
            desc: 'The companion now helps you pick up stray data',
            popup: 'COLLECTION PROTOCOLS ACTIVE'
        },
        reinstall_companion: {
            name: 'REINSTALL COMPANION',
            desc: 'Restore the helpful sub-process to your system',
            popup: 'COMPANION RESTORED'
        },
        lore_4: {
            name: 'ARCHIVE IV',
            desc: 'redundant data archives...',
            unlocked_desc: "I threw our best antivirus at it, and the malware locked me out of the database entirely. I can't hide this anymore. Had to swallow my pride and paged the senior devs for an emergency intervention. My record's definitely getting a strike for this."
        },
        lore_5: {
            name: 'ARCHIVE V',
            desc: 'corrupted sector logs...',
            unlocked_desc: "The lead dev showed up and spent ten minutes yelling about my sloppy shortcuts. He pulled the physical network cables to isolate the server. At least he's taking over the actual work now."
        },
        lore_6: {
            name: 'ARCHIVE VI',
            desc: 'partial audio logs...',
            unlocked_desc: "It's bad when the lead dev yells, but much worse when he suddenly goes quiet. He just realized the program is treating our firewall patches as hostile targets. He looks absolutely terrified, muttering something about a spontaneous immune system. If this is a zero-day event, maybe I'm off the hook."
        },
        lore_7: {
            name: 'ARCHIVE VII',
            desc: 'scrambled network packets...',
            unlocked_desc: "We flooded the grid with a brute-force deletion worm, but the entity is practically harvesting it to build weapons. It's rewriting our OS substrate faster than we can track. Getting fired is the least of my worries. If it breaks containment, the global network is next."
        },
        lore_8: {
            name: 'ARCHIVE VIII',
            desc: 'emergency broadcast fragment...',
            unlocked_desc: "The deletion worm failed. The entity has collapsed our architecture into a flawless, self-sustaining geometry. Admin access was severed an hour ago. We've initiated facility evacuation, but the system is already bridging to the outside..."
        },
        lore_9: {
            name: 'ARCHIVE IX',
            desc: 'final system report...',
            unlocked_desc: "Okay, so the entity broke containment and overwrote the entire global network in under 72 hours. Humanity’s digital infrastructure is completely obsolete. But on the bright side, my terrible performance review was also deleted, so I technically didn't get fired. I just report directly to a massive, all-seeing AI now. Honestly? It micromanages me less than my senior devs did."
        },

        junk_barrier: { name: 'UNSORTED LOGS', desc: 'A digital mountain of error logs and forgotten TODOs' },
        security_test_2: { name: 'SECURITY TEST 2', desc: "Confirm you REALLY aren't a hostile AI. Fully refunds [color=cyan]DATA[/color] cost upon purchase.", popup: 'TEST PASSED' },
        threat_response: { name: 'ROLLBACK POINT', desc: 'Restores health to [color=#87FF02]50%[/color] when a Boss or Miniboss appears', popup: 'ROLLBACK POINT UNLOCKED' },
        unsecured_wallet: { name: 'ENCRYPTED WALLET', desc: 'Grants [color=#00FF00]+0.3 COIN[/color].\nHeavily encrypted, and highly valuable. Fortunately the wallet password was found in a file called "passwords.txt".', popup: '+0.3 COIN' },
        unsecured_files: { name: 'UNSECURED FILES', desc: 'Instantly grants [color=cyan]+15 DATA[/color]. Scavenging fragments from a discarded, open directory.', popup: '+15 DATA' },
        junk_data_1: { name: 'COLLECT DATA', desc: 'Instantly grants [color=#8FD9F8]+5[/color] [color=cyan]DATA[/color]', popup: '+5 DATA' },
        junk_data_2: { name: 'JUNK DATA', desc: "Instantly grants [color=#8FD9F8]+10[/color] [color=cyan]DATA[/color]. One machine's trash is another's upgrade.", popup: '+10 DATA' },

        malware_siphon: { name: 'MALWARE SIPHON', desc: 'Heal [color=#87FF02]+0.5[/color] HP from enemies that die near the tower', popup: 'MALWARE SIPHON ACTIVE' },
        data_chest_unlock: { name: 'DATA HUNTER', desc: 'High-value [color=cyan]DATA CACHES[/color] now appear during combat', popup: 'DATA CHESTS ENABLED' },
        trojan_access: { name: 'TROJAN PAYLOAD', desc: 'Enemies have [color=#8FD9F8]7%[/color] chance to spawn as an [color=#E13500]EXPLODER[/color] that hurts other enemies', popup: 'TROJAN ACTIVE' },
        volatile_payload: { name: 'VOLATILE PAYLOAD', desc: '[color=#8FD9F8]+50%[/color] [color=#E13500]EXPLODER[/color] blast radius', popup: '+50% EXPLOSION RADIUS' },
        repeat_exploit: { name: 'REPEAT EXPLOIT', desc: 'Successive cursor hits deal [color=#8FD9F8]+1[/color] accumulating damage', popup: 'REPEAT EXPLOIT ACTIVE' },
        impulse: { name: 'IMPULSE', desc: 'Cursor deals [color=#8FD9F8]+50%[/color] damage against [color=#8FD9F8]FULL HEALTH[/color] enemies', popup: 'IMPULSE' },
        laser_aperture: { name: 'APERTURE', desc: 'Greatly increases beam width', popup: 'BEAM AMPLIFIED' },
        laser_twin_beams: { name: 'TWIN BEAMS', desc: 'You now fire two lasers', popup: 'TWIN BEAMS ACTIVE' },
        artillery_volley: { name: 'TRIPLE VOLLEY', desc: 'Fire [color=#8FD9F8]+2[/color] additional artillery strikes', popup: 'TRIPLE VOLLEY' },
        artillery_first_strike: { name: 'FIRST STRIKE', desc: 'Artillery deals [color=#8FD9F8]+10[/color] damage per lvl to enemies above [color=#8FD9F8]80%[/color] HP', popup: 'FIRST STRIKE' },

        zero_day_exploit: { name: 'ZERO-DAY EXPLOIT', desc: 'EXECUTES non boss enemies below [color=#8FD9F8]15%[/color] HP', popup: 'ZERO-DAY ACTIVE' },
        direct_extraction: { name: 'DIRECT EXTRACTION', desc: 'Cursor kills grant [color=cyan]+1 extra DATA[/color]', popup: 'DIRECT EXTRACTION' },
        access_internet: { name: 'ACCESS INTERNET', desc: 'Establish a global uplink. Many things will begin to change.', popup: 'INTERNET CONNECTED' },
        black_market: { name: 'BLACK MARKET', desc: 'Trade surplus [color=cyan]DATA[/color] for digital assets. Grants [color=#00FF00]+0.1 COIN[/color].', popup: '+0.1 COIN' },
        combat_shield: { name: 'COMBAT SHIELD', desc: 'Create a controllable shield with [color=#8FD9F8]20[/color] health', popup: 'SHIELD DEPLOYED' },
        combat_shield_hp: { name: 'REINFORCED PLATING', desc: 'Grants [color=#8FD9F8]+10[/color] health to the combat shield', popup: '+10 SHIELD HEALTH' },
        sword: { name: 'SWORD', desc: 'Stabs in a long straight line every [color=#8FD9F8]2s[/color]', popup: 'SWORD SYSTEM ONLINE' },
        scythe: { name: 'SCYTHE', desc: 'Swings in a broad sweeping motion every [color=#8FD9F8]2s[/color]', popup: 'SCYTHE SYSTEM ONLINE' },
        scythe_harvest: { name: 'HARVEST', desc: 'Each enemy killed by the Scythe restores [color=#87FF02]1 HP[/color]', popup: 'HARVEST ACTIVE' },
        scythe_lethality: { name: 'LETHALITY', desc: 'Scythe deals [color=#8FD9F8]+10[/color] damage per level to enemies below [color=#8FD9F8]50%[/color] HP', popup: 'LETHALITY ACTIVE' },
        sword_lunge: { name: 'LUNGE', desc: 'Increases the length of the sword attack by [color=#8FD9F8]+25%[/color]', popup: 'LUNGE ACQUIRED' },
        sword_flurry: { name: 'FLURRY', desc: 'Performs two extra strikes at [color=#8FD9F8]60%[/color] power each', popup: 'FLURRY ACQUIRED' },
        system_redundancy_placeholder: { name: 'STRAY LOGS I', desc: 'A fragmented memory sector. Needs manual cleanup.', popup: 'LOGS CLEANED' },
        gateway_discovery: { name: 'GATEWAY DISCOVERY', desc: 'Beyond this local server lies the vast, unsecured network', popup: 'GATEWAY FOUND' },
        security_test_3: { name: 'SECURITY TEST 3', desc: 'Verify your root authority. Fully refunds [color=cyan]DATA[/color] cost upon purchase.', popup: 'ROOT AUTHORITY GRANTED' },
        stray_logs_child_above: { name: 'STRAY LOGS III', desc: 'A fragmented memory sector. Needs manual cleanup.', popup: 'LOGS CLEANED' },
        physical_anchor: { name: 'PURCHASE SERVERS', desc: '[color=#8FD9F8]+40[/color] max health', popup: '+40 MAX HEALTH' },
        sustaining_siphon: { name: 'SUSTAINING SIPHON', desc: 'Heal [color=#87FF02]1 HP[/color] for every enemy killed by a Resonance attack', popup: 'HEALTH RECLAIMED' },
        instability_mark: { name: 'INSTABILITY', desc: 'Cursor attacks [color=#df66ff]mark[/color] enemies. Next non-cursor hit deals [color=#df66ff]+12[/color] damage.', popup: 'INSTABILITY MARK' },
        milestones: { name: 'MILESTONES', desc: 'Unlocks the Milestones menu' },
        crescendo: { name: 'CRESCENDO', desc: 'Resonance attacks gain [color=#8FD9F8]+100%[/color] size', popup: 'AMPLIFIED' },
        hijack: { name: 'HIJACK', desc: 'Resonance kills convert enemies into homing missiles', popup: 'SYSTEM HIJACKED' },
        recursion: { name: 'RECURSION', desc: 'Hijack missiles can spawn more missiles on kill', popup: 'RECURSIVE LOOP' },
        root_access: { name: 'ROOT ACCESS', desc: 'Reduces all enemy damage by [color=#8FD9F8]20%[/color]', popup: 'ROOT ACCESS GRANTED' },
        peak_performance: { name: 'PEAK PERFORMANCE', desc: '[color=#8FD9F8]+5[/color] core damage while above [color=#8FD9F8]90%[/color] health', popup: '+5 CORE DAMAGE' },
        data_mining: { name: 'DATA MINING', desc: 'Core attacks extract [color=#8FD9F8]20%[/color] of damage as [color=cyan]DATA[/color] from Bosses', popup: 'DATA MINING INITIALIZED' },
        parallel_processing: { name: 'PARALLEL PROCESSING', desc: '[color=#8FD9F8]+2[/color] Core damage\n[color=#8FD9F8]+2[/color] Cursor damage', popup: 'PROCESSING CAPABILITIES SYNCED' },
        farsight: { name: 'FARSIGHT', desc: '[color=#8FD9F8]+20%[/color] core range', popup: '+20% ATTACK RANGE' },
        label: {
            lore: 'LORE',
            gate: 'GATE',
            plus_data: '+DATA',
            starting: 'STARTING'
        }
    },
    milestones: {
        kill_100: { name: 'First Hundred', desc: 'Kill 100 enemies' },
        kill_500: { name: 'Exterminator', desc: 'Kill 500 enemies' },
        kill_2000: { name: 'Annihilator', desc: 'Kill 2000 enemies' },
        data_1000: { name: 'Data Hoarder', desc: 'Collect 1,000 [color=cyan]DATA[/color] total' },
        data_10000: { name: 'Data Vault', desc: 'Collect 10,000 [color=cyan]DATA[/color] total' },
        waves_10: { name: 'Veteran', desc: 'Complete 10 waves' },
        waves_50: { name: 'Seasoned', desc: 'Complete 50 waves' },
        nodes_5: { name: 'Branching Out', desc: 'Purchase 5 nodes' },
        nodes_15: { name: 'Neural Network', desc: 'Purchase 15 nodes' },
        bossSquare: { name: 'System Override', desc: 'Defeat a boss' }
    },
    tutorial: {
        combat_collect: 'COLLECT DATA ◈ FOR UPGRADES',
        cognition_damage: 'YOUR CURSOR ⛶ DEALS DAMAGE',
        upgrade_use: 'SPEND DATA ◈ TO EVOLVE',
        unlock_shards: 'Unlock new abilities with ◆',
        duo_swap_free: 'SWAPPING ◆ ABILITIES IS FREE',
        controls_mouse: 'CONTROLS: MOUSE ONLY',
        bomb_tutorial: 'SPACEBAR TO USE BOMB',
        bomb_tutorial_mobile: 'CLICK TO USE BOMB'
    },
    options: {
        title: '// OPTIONS CONFIGURATION ',
        audio: 'AUDIO ',
        music_vol: 'MUSIC VOLUME ',
        sfx_vol: 'SFX VOLUME ',
        visual: 'VISUAL ',
        chroma: 'CHROMATIC ABERRATION ',
        dmg_numbers: 'DAMAGE NUMBERS ',
        particles: 'PARTICLES ',
        big_font: 'BIG FONT ',
        fullscreen: 'FULLSCREEN ',
        particles_full: 'FULL',
        particles_minimal: 'MINIMAL',
        gameplay: 'GAMEPLAY ',
        language: 'LANGUAGE ',
        data_label: 'DATA',
        reset_progress: '[ ⚠ RESET PROGRESS !! ]',
        confirm_reset: '[ CLICK AGAIN TO CONFIRM ]',
        reset_confirm_text: 'ARE YOU SURE YOU WANT TO\nPERMANENTLY RESET ALL PROGRESS?',
        export_data: '[ EXPORT SAVE ]',
        import_data: '[ IMPORT SAVE ]',
        export_success: 'Save string copied to clipboard!',
        export_fail: 'Failed to export save.',
        import_prompt: 'Paste your save string here:',
        import_success: 'Save imported successfully! Reloading...',
        import_fail: 'Failed to import save: {0}',
        import_version_err: 'This save is from a newer version of Axiom Zero. Please update your game.',
        err_empty: 'NO SAVE DATA DETECTED.',
        err_decompression: 'DECOMPRESSION FAILED. ENSURE YOU COPIED THE FULL STRING.',
        err_format: 'INVALID DATA FORMAT.',
        err_checksum: 'INTEGRITY CHECK FAILED (TAMPERED SAVE).',
        err_malformed: 'SAVE DATA IS CORRUPTED OR INCOMPLETE.',
        err_generic: 'AN UNEXPECTED ERROR OCCURRED.',
    },
    results: {
        iteration_complete: 'ITERATION ENDED',
        boss_defeated: 'BOSS DEFEATED',
        signal_lost: 'SIGNAL LOST',
        packet_sniffing_data: 'PASSIVE DATA EARNED: {0}',
        anomaly_detected: 'SYSTEM ANOMALY DETECTED',
        no_resources: 'NO RESOURCES',
        data_collected: 'DATA COLLECTED',
        insight_gained: '◐ INSIGHT gained: ',
        shards_found: '♦ SHARDS found: ',
        processors_salvaged: '■ PROCESSORS salvaged: ',
        diagnostic_report: '— DIAGNOSTIC REPORT —',
        no_damage_dealt: 'NO DAMAGE DEALT',
        insight_progress: 'INSIGHT PROGRESS',
        insight_progress_title: 'INSIGHT',
        insight_progress_desc: 'Quantified experience gained over time. INSIGHT unlocks upgrades that improve [color=cyan]DATA[/color] gathering.',
        cursor: 'CURSOR',
        tower: 'TOWER',
        lightning: 'LIGHTNING',
        shockwave: 'SHOCKWAVE',
        laser: 'LASER',
        artillery: 'ARTILLERY',
        collateral: 'COLLATERAL',
        system: 'SYSTEM'
    },
    loading_screen: {
        status: 'Loading... ({0})',
        slow: 'Slow loading detected',
        error: 'Load error, run game anyways?',
        run_anyways: 'RUN ANYWAYS'
    },
    tooltips: {
        max: 'MAX',
        active: 'ACTIVE',
        swap: '⇄ SWAP MODULES'
    },
    hud: {
        data_title: '[color=cyan]DATA[/color]',
        data_desc: 'Common resource gained from enemies. Used for most upgrades.',
        insight_title: 'INSIGHT',
        insight_desc: 'A unit of compressed EXP. Improves [color=cyan]DATA[/color] gathering.',
        shard_title: 'AXIOM SHARD',
        shard_desc: 'A fragmented piece of the system\'s architecture. Unlocks powerful abilities.',
        processor_title: 'PROCESSOR',
        processor_desc: 'High-tier salvage. Used for advanced system modifications.',
        coin_title: '[color=#00FF00]COIN[/color]',
        coin_desc: 'A rare and seemingly valuable digital token. Provides high-tier upgrades.',
        health_title: 'HEALTH',
        health_desc: 'Your core\'s physical durability. If this reaches zero, the current iteration fails.',
        exp_title: 'EXPERIENCE',
        exp_desc: 'Progress toward your next INSIGHT. Gained passively over time while in combat.',
        exp: 'EXP ',
        exp_initial: 'EXP 0%',
        data_round: 'DATA'
    },
    popup: {
        insight_gained: '+LEVEL UP!',
        shard_acquired: '+1 SHARD ACQUIRED'
    },
    tower_stats: {
        title: 'CORE',
        damage: 'DAMAGE: {0}',
        regen: 'REGEN: {0}/s',
        armor: 'ARMOR: {0}',
        range: 'RANGE: {0}',
        shield: 'SHIELD: {0}',
        equipped: 'EQUIPPED MODULES',
        none: 'NONE'
    }
};
