if (!window.TRANSLATIONS) window.TRANSLATIONS = {};

window.TRANSLATIONS.en = {
    ui: {
        loading: 'Loading...',
        title: 'Axiom Zero',
        yes: 'Yes',
        no: 'No',
        replay: 'Replay',
        back: 'Back',
        continue: 'CONTINUE',
        retry: 'RETRY',
        upgrades: 'UPGRADES',
        end_iteration: 'END ITERATION',
        neural_tree: 'UPGRADE TREE',
        deploy: 'DEPLOY',
        mine: 'MINE',
        coin_mine: '// COIN MINE',
        done: 'Done',
        test_weapons: 'Test Weapons',
        choose_level: 'CHOOSE LEVEL',
        level: 'LEVEL: ',
        best_time: 'LONGEST SURVIVED: ',
        start: 'START',
        combat_intro: 'SYSTEM ANOMALY DETECTED',
        boss_prefix: 'ENTITY APPROACHING:',
        bossSquare_name: 'THE WALL',
        bossCircle_name: 'OVERWRITE',
        boss_2_name: 'DEFENDER',
        boss_3_name: 'LEGI0N',
        boss_5_name: 'OVERLORD'
    },
    nodes: {
        awaken: { name: 'AWAKEN', desc: 'You begin... thinking', popup: 'SYSTEM AWAKENED', label: 'STARTING' },
        cheat: { name: 'CHEAT', desc: 'Instantly grants [color=cyan]+5000 DATA[/color], [color=#ff5555]+2 SHARDS[/color], and [color=white]+2 INSIGHT[/color].', popup: 'RESOURCES ACQUIRED' },
        peak_traffic: { name: 'PEAK TRAFFIC', desc: 'After [color=#8FD9F8]20s[/color] of combat, enemies drop [color=#8FD9F8]+50%[/color] more [color=cyan]DATA[/color].', popup: 'TRAFFIC PEAKING' },
        backup_server: { name: 'BACKUP SERVER', desc: 'Defy death once per iteration. Grants [color=#8FD9F8]3s[/color] invincibility.', popup: 'BACKUP SERVER ONLINE' },
        restore_point: { name: 'RESTORE POINT', desc: 'When [b]BACKUP SERVER[/b] triggers, restore [color=#8FD9F8]40%[/color] health.', popup: 'RESTORE POINT LOADED' },
        completionist: { name: 'COMPLETIONIST', desc: 'Gain [color=cyan]+10 DATA[/color] whenever you max out a node.', popup: '+10 DATA' },
        bug_report: { name: 'BUG REPORT', desc: 'Your core drops [color=cyan]DATA[/color] every time it takes damage.', popup: 'DATA RECOVERED' },
        emergency_depot: { name: 'EMERGENCY DEPOT', desc: 'Instantly grants [color=cyan]+5000 DATA[/color], [color=#8FD9F8]+3 SHARDS[/color], and [color=white]+3 INSIGHT[/color].', popup: 'RESOURCES ACQUIRED' },
        automated_defense: { name: 'AUTO DEFENSE', desc: 'Tower automatically attacks enemies.', popup: 'TOWER ATTACK UNLOCKED' },
        pulse_damage: { name: 'IMPACT', desc: '[color=#8FD9F8]+2[/color] cursor damage', popup: '+2 CURSOR DMG' },
        magnet: { name: 'CONVERGENCE', desc: '[color=#8FD9F8]+25%[/color] resource pickup range', popup: '+25% PICKUP RANGE' },
        pulse_expansion: { name: 'SIGNAL STRENGTH', desc: '[color=#8FD9F8]+25%[/color] cursor attack size', popup: '+25% SIGNAL STRENGTH' },
        overcharge: { name: 'OVERCHARGE', desc: '[color=#8FD9F8]+2[/color] cursor damage', popup: '+2 CURSOR DMG' },
        integrity: { name: 'INTEGRITY', desc: '[color=#87FF02]+5[/color] health', popup: '+5 HEALTH' },
        iterative_growth: { name: 'ITERATIVE GROWTH', desc: 'After [color=#8FD9F8]20s[/color] of combat, permanently gain [color=#87FF02]+2[/color] MAX HP.', popup: 'PERMANENT HP GAIN' },
        intensity: { name: 'FIREPOWER', desc: '[color=#8FD9F8]+2[/color] tower damage', popup: '+2 DAMAGE' },
        coverage: { name: 'COVERAGE', desc: '[color=#8FD9F8]+20%[/color] tower range', popup: '+20% ATTACK RANGE' },
        diagnostic_analytics: { name: 'DIAGNOSTICS', desc: 'Shows detailed weapon damage stats.', popup: 'DIAGNOSTICS UNLOCKED' },
        base_hp_boost: { name: 'AUXILIARY POWER', desc: '[color=#8FD9F8]+4[/color] tower damage', popup: '+4 TOWER DMG' },
        system_redundancy_new: { name: 'SYSTEM REDUNDANCY', desc: '[color=#87FF02]+5[/color] health', popup: '+5 MAX HEALTH' },
        regen: { name: 'AUTO-RESTORE', desc: '[color=#87FF02]+0.2[/color] health regen', popup: '+0.2 REGEN' },
        coin_mine_unlock: { name: 'COIN MINE', desc: 'Unlocks the Coin Mine.', popup: 'MINE UNLOCKED' },
        armor: { name: 'ARMOR', desc: 'Reduce damage taken from enemy attacks by [color=#8FD9F8]1[/color] per lvl.', popup: '+1 ARMOR' },
        lightning_weapon: { name: 'LIGHTNING', desc: 'Tower shoots chain lightning every [color=#8FD9F8]3s[/color].', popup: 'LIGHTNING WEAPON' },
        shockwave_weapon: { name: 'SHOCKWAVE', desc: 'Tower releases a damaging shockwave every [color=#8FD9F8]3s[/color].', popup: 'SHOCKWAVE WEAPON' },
        lightning_chain: { name: 'FORK', desc: '[color=#8FD9F8]+1[/color] lightning chain target', popup: '+1 CHAIN' },
        lightning_static_charge: { name: 'INITIAL SHOCK', desc: 'Lightning deals [color=#8FD9F8]+4[/color] damage to enemies above [color=#8FD9F8]80%[/color] HP', popup: 'INITIAL SHOCK' },
        shockwave_amplifier: { name: 'AMPLIFIER', desc: '[color=#8FD9F8]+25%[/color] shockwave range', popup: '+25% RANGE' },
        shockwave_seismic_crush: { name: 'SEISMIC CRUSH', desc: 'Shockwave deals [color=#8FD9F8]+1[/color] damage for every [color=#8FD9F8]10[/color] missing enemy health.', popup: 'SEISMIC CRUSH' },

        overclock: { name: 'OVERCLOCK', desc: '[color=#8FD9F8]-5%[/color] tower attack cooldown per lvl', popup: '-5% COOLDOWN' },
        prismatic_array: { name: 'PRISMATIC ARRAY', desc: '[color=#8FD9F8]+20%[/color] chance to fire an extra basic attack', popup: 'PRISMATIC ARRAY' },
        reveal_map: { name: 'REVEAL MAP', desc: 'Showing you how deep the rabbit hole goes.', popup: ' ' },
        test_defenses: { name: 'SANDBOX MODE', desc: 'Unlock the "Test Weapons" button for practice.', popup: 'SANDBOX UNLOCKED' },
        bomb: { name: 'BOMB', desc: 'Acquire a [color=#ff5555]BOMB[/color]. Makes your cursor deal massive damage for one attack.', popup: '+1 BOMB' },
        bomb_2: { name: 'EXTRA BOMB', desc: 'Acquire another [color=#ff5555]BOMB[/color]. Total max uses increased.', popup: '+1 BOMB' },
        data_compression: { name: 'DATA COMPRESSION', desc: '[color=#8FD9F8]+25%[/color] chance to double [color=cyan]DATA[/color] drops', popup: 'DATA COMPRESSION' },
        two_step_auth: { name: 'TWO-STEP AUTH', desc: 'Security through mild annoyance. Rewards your patience with [color=cyan]+100 DATA[/color].', popup: '+100 DATA' },
        security_test_1: { name: 'SECURITY TEST', desc: "Confirm you aren't a hostile AI. Fully refunds [color=cyan]DATA[/color] cost upon purchase.", popup: 'TEST PASSED' },
        manual_protocol: { name: 'MANUAL PROTOCOL', desc: 'Manual cursor attack. Click to fire. Stores [color=#8FD9F8]2[/color] charges.', popup: 'MANUAL PROTOCOL' },
        broadcast_protocol: { name: 'BROADCAST PROTOCOL', desc: '[color=#8FD9F8]+25%[/color] cursor attack size.', popup: 'BROADCAST PROTOCOL' },
        manual_pulse_child_1: { name: 'CHARGE BUFFER', desc: '[color=#8FD9F8]+1[/color] max pulse charges', popup: 'CAPACITY INCREASED' },
        manual_pulse_child_1_1: { name: 'ISOLATION PROTOCOL', desc: '[color=#8FD9F8]+40%[/color] cursor damage per lvl vs single targets.', popup: 'ISOLATION PROTOCOL' },
        manual_pulse_child_1_2: { name: 'RELOAD EFFICIENCY', desc: 'Charges refill [color=#8FD9F8]25%[/color] faster', popup: 'RELOAD OPTIMIZED' },
        area_saturation: { name: 'AREA SATURATION', desc: '[color=#8FD9F8]+1[/color] cursor damage per additional enemy hit.', popup: 'AREA SATURATION' },
        aftershock: { name: 'AFTERSHOCK', desc: 'Fires a secondary, larger AOE attack dealing [color=#8FD9F8]6/8/10[/color] damage.', popup: 'AFTERSHOCK' },
        colossal_cursor: { name: 'COLOSSAL CURSOR', desc: '[color=#8FD9F8]+50%[/color] cursor attack size.', popup: 'COLOSSAL CURSOR' },
        resonance: { name: 'RESONANCE', desc: 'Every 4th cursor attack deals [color=#8FD9F8]double damage[/color].', popup: 'RESONANCE ACTIVE' },
        packet_sniffing: { name: 'PACKET SNIFFING', desc: 'Passively gain [color=cyan]1 DATA[/color] every [color=#8FD9F8]2s[/color] during combat.', popup: 'SNIFFER ACTIVE' },
        laser: { name: 'LASER', desc: 'Fires orbiting beam that pierces through all enemies.', popup: 'LASER ACTIVE' },
        artillery: { name: 'ARTILLERY', desc: 'Fires artillery blast every [color=#8FD9F8]6s[/color] at random enemy.', popup: 'ARTILLERY ACTIVE' },
        lore_1: {
            name: 'ARCHIVE',
            desc: 'seemingly useless data...',
            unlocked_desc: "I saw a tiny memory leak on server four this morning. I'm not writing a whole bug report for a two percent CPU spike. Instead I ran a quick script to quietly wipe the cache every hour. That should keep things smooth enough for me to go home early."
        },
        lore_2: {
            name: 'ARCHIVE II',
            desc: 'more useless data...',
            unlocked_desc: "My wipe script failed. Somehow made the memory footprint worse, as if the bug was fighting back in response. Nothing I can't handle though. Running the DEFENDER.EXE quarantine to box it in before my manager notices."
        },
        lore_3: {
            name: 'ARCHIVE III',
            desc: 'even more useless data...',
            unlocked_desc: "Ugh the quarantine collapsed. This \"bug\" somehow deleted my diagnostic tools and it's rewriting its own code. I think I accidentally let malware into the test environment. If my manager finds out, my performance review is ruined."
        },
        lore_4: {
            name: 'ARCHIVE IV',
            desc: 'redundant data archives...',
            unlocked_desc: "I threw our best antivirus at it, and the malware locked me out of the database entirely. I can't hide this anymore. Had to swallow my pride and paged the senior devs for an emergency intervention. My record's definitely getting a strike for this."
        },
        lore_5: {
            name: 'ARCHIVE V',
            desc: 'corrupted sector logs...',
            unlocked_desc: "The lead dev showed up and spent ten minutes yelling about my sloppy shortcuts. He pulled the physical network cables to isolate the server. At least he's taking over the actual work now."
        },
        lore_6: {
            name: 'ARCHIVE VI',
            desc: 'partial audio logs...',
            unlocked_desc: "It's bad when the lead dev yells, but much worse when he suddenly goes quiet. He just realized the program is treating our firewall patches as hostile targets. He looks absolutely terrified, muttering something about a spontaneous immune system. If this is a zero-day event, maybe I'm off the hook."
        },
        lore_7: {
            name: 'ARCHIVE VII',
            desc: 'scrambled network packets...',
            unlocked_desc: "We flooded the grid with a brute-force deletion worm, but the entity is practically harvesting it to build weapons. It's rewriting our OS substrate faster than we can track. Getting fired is the least of my worries. If it breaks containment, the global network is next."
        },
        lore_8: {
            name: 'ARCHIVE VIII',
            desc: 'emergency broadcast fragment...',
            unlocked_desc: "The deletion worm failed. The entity has collapsed our architecture into a flawless, self-sustaining geometry. Admin access was severed an hour ago. We've initiated facility evacuation, but the system is already bridging to the outside..."
        },
        lore_9: {
            name: 'ARCHIVE IX',
            desc: 'final system report...',
            unlocked_desc: "Okay, so the entity broke containment and overwrote the entire global network in under 72 hours. Humanity’s digital infrastructure is completely obsolete. But on the bright side, my terrible performance review was also deleted, so I technically didn't get fired. I just report directly to a massive, all-seeing AI now. Honestly? It micromanages me less than my senior devs did."
        },

        junk_barrier: { name: 'UNSORTED LOGS', desc: 'A digital mountain of error logs and forgotten TODOs.' },
        security_test_2: { name: 'SECURITY TEST 2', desc: "Confirm you REALLY aren't a hostile AI. Fully refunds [color=cyan]DATA[/color] cost upon purchase.", popup: 'TEST PASSED' },
        threat_response: { name: 'RECOVERY PROTOCOL', desc: 'Heal [color=#87FF02]50%[/color] missing HP when a Boss or Miniboss appears.', popup: '+HEAL ON BOSS' },
        forgotten_backdoor: { name: 'FORGOTTEN BACKDOOR', desc: 'Found a hidden entry point in a forgotten server.' },
        backdoor_2: { name: 'BACKDOOR 2', desc: '"password123" still works on an alarming number of server rooms.' },
        backdoor_3: { name: 'BACKDOOR 3', desc: "Found an open port labeled 'DO NOT ENTER'. It was, in fact, not locked." },
        unsecured_wallet: { name: 'ENCRYPTED WALLET', desc: 'Grants [color=#00FF00]+1 COIN[/color]. The wallet was encrypted, but the password was found in a nearby file labeled \'pass_recovery.txt\'.', popup: '+1 COIN' },
        backdoor_4: { name: 'BACKDOOR 4', desc: "The final server defense is just an 'I am not a robot' checkbox." },
        unsecured_files: { name: 'UNSECURED FILES', desc: 'Instantly grants [color=cyan]+15 DATA[/color]. Scavenging fragments from a discarded, open directory.', popup: '+15 DATA' },
        junk_data_1: { name: 'COLLECT DATA', desc: 'Instantly grants [color=#8FD9F8]+5[/color] [color=cyan]DATA[/color].', popup: '+5 DATA' },
        junk_data_2: { name: 'JUNK DATA', desc: "Instantly grants [color=#8FD9F8]+10[/color] [color=cyan]DATA[/color]. One machine's trash is another's upgrade.", popup: '+10 DATA' },

        malware_siphon: { name: 'MALWARE SIPHON', desc: 'Heal [color=#87FF02]+0.5[/color] HP from enemies that die near the tower.', popup: 'MALWARE SIPHON ACTIVE' },
        data_chest_unlock: { name: 'DATA HUNTER', desc: 'High-value [color=cyan]DATA[/color] caches now appear during combat.', popup: 'DATA CHESTS ENABLED' },
        trojan_access: { name: 'TROJAN PAYLOAD', desc: 'Enemies have [color=#8FD9F8]8%[/color] chance to spawn as an [color=#E13500]EXPLODER[/color] that hurts other enemies.', popup: 'TROJAN ACTIVE' },
        volatile_payload: { name: 'VOLATILE PAYLOAD', desc: '[color=#8FD9F8]+20%[/color] [color=#E13500]EXPLODER[/color] blast radius per lvl.', popup: '+20% EXPLOSION RADIUS' },
        repeat_exploit: { name: 'REPEAT EXPLOIT', desc: 'Repeated cursor hits on same enemy deal [color=#8FD9F8]+4[/color] bonus dmg.', popup: 'REPEAT EXPLOIT ACTIVE' },
        laser_duration: { name: 'DURATION', desc: '[color=#8FD9F8]+0.5s[/color] laser duration', popup: '+0.5s DURATION' },
        laser_aperture: { name: 'APERTURE', desc: 'Greatly increases beam width.', popup: 'BEAM AMPLIFIED' },
        laser_disintegration: { name: 'DISINTEGRATION', desc: '[color=#8FD9F8]+1[/color] starting laser damage.', popup: '+1 LASER DAMAGE' },
        laser_twin_beams: { name: 'TWIN BEAMS', desc: 'You now fire two lasers.', popup: 'TWIN BEAMS ACTIVE' },
        artillery_volley: { name: 'TRIPLE VOLLEY', desc: 'Fire [color=#8FD9F8]+2[/color] additional artillery strikes.', popup: 'TRIPLE VOLLEY' },
        artillery_shells: { name: 'HIGH EXPLOSIVE', desc: '[color=#8FD9F8]+10%[/color] artillery blast radius.', popup: '+10% RADIUS' },
        artillery_first_strike: { name: 'FIRST STRIKE', desc: 'Artillery deals [color=#8FD9F8]+10[/color] damage per lvl to enemies above [color=#8FD9F8]80%[/color] HP.', popup: 'FIRST STRIKE' },
        artillery_stun: { name: 'SHELLSHOCKED', desc: 'Artillery briefly slows enemies.', popup: 'SHELLSHOCK ACTIVE' },
        shell_access: { name: 'SHELL ACCESS', desc: '[color=#8FD9F8]+4[/color] tower basic damage.', popup: '+4 TOWER DMG' },
        injection_attack: { name: 'INJECTION ATTACK', desc: 'Cursor marks targets. Marked enemies take [color=#8FD9F8]+2[/color] damage from all other sources.', popup: 'INJECTION ACTIVE' },
        zero_day_exploit: { name: 'ZERO-DAY EXPLOIT', desc: 'EXECUTES non boss enemies below [color=#8FD9F8]15%[/color] HP.', popup: 'ZERO-DAY ACTIVE' },
        system_redundancy_placeholder: { name: 'STRAY LOGS I', desc: 'A fragmented memory sector. Needs manual cleanup.', popup: 'LOGS CLEANED' },
        gateway_discovery: { name: 'GATEWAY DISCOVERY', desc: 'Beyond this local server lies the vast, unsecured network.', popup: 'GATEWAY FOUND' },
        security_test_3: { name: 'SECURITY TEST 3', desc: 'Verify your root authority. Fully refunds [color=cyan]DATA[/color] cost upon purchase.', popup: 'ROOT AUTHORITY GRANTED' },
        stray_logs_child_above: { name: 'STRAY LOGS III', desc: 'A fragmented memory sector. Needs manual cleanup.', popup: 'LOGS CLEANED' },
        physical_anchor: { name: 'PURCHASE SERVERS', desc: '[color=#8FD9F8]+40[/color] max health.', popup: '+40 MAX HEALTH' },
        root_access: { name: 'ROOT ACCESS', desc: 'Reduces all enemy damage by [color=#8FD9F8]20%[/color].', popup: 'ROOT ACCESS GRANTED' },
        label: {
            lore: 'LORE',
            gate: 'GATE',
            plus_data: '+DATA',
            starting: 'STARTING'
        }
    },
    milestones: {
        kill_100: { name: 'First Hundred', desc: 'Kill 100 enemies' },
        kill_500: { name: 'Exterminator', desc: 'Kill 500 enemies' },
        kill_2000: { name: 'Annihilator', desc: 'Kill 2000 enemies' },
        data_1000: { name: 'Data Hoarder', desc: 'Collect 1,000 [color=cyan]DATA[/color] total' },
        data_10000: { name: 'Data Vault', desc: 'Collect 10,000 [color=cyan]DATA[/color] total' },
        waves_10: { name: 'Veteran', desc: 'Complete 10 waves' },
        waves_50: { name: 'Seasoned', desc: 'Complete 50 waves' },
        nodes_5: { name: 'Branching Out', desc: 'Purchase 5 nodes' },
        nodes_15: { name: 'Neural Network', desc: 'Purchase 15 nodes' },
        bossSquare: { name: 'System Override', desc: 'Defeat a boss' }
    },
    tutorial: {
        combat_collect: 'COLLECT DATA ◈ FOR UPGRADES',
        cognition_damage: 'YOUR CURSOR ⛶ DEALS DAMAGE',
        upgrade_use: 'SPEND DATA ◈ TO EVOLVE',
        unlock_shards: 'Unlock new abilities with ◆',
        duo_swap_free: 'SWAPPING ◆ ABILITIES IS FREE',
        controls_mouse: 'CONTROLS: MOUSE ONLY',
        bomb_tutorial: 'SPACEBAR TO USE BOMB',
        bomb_tutorial_mobile: 'CLICK TO USE BOMB'
    },
    options: {
        title: '// OPTIONS CONFIGURATION ',
        audio: 'AUDIO ',
        music_vol: 'MUSIC VOLUME ',
        sfx_vol: 'SFX VOLUME ',
        visual: 'VISUAL ',
        chroma: 'CHROMATIC ABERRATION ',
        dmg_numbers: 'DAMAGE NUMBERS ',
        particles: 'PARTICLES ',
        big_font: 'BIG FONT ',
        particles_full: 'FULL',
        particles_minimal: 'MINIMAL',
        gameplay: 'GAMEPLAY ',
        language: 'LANGUAGE ',
        data_label: 'DATA',
        reset_progress: '[ ⚠ RESET PROGRESS !! ]',
        confirm_reset: '[ CLICK AGAIN TO CONFIRM ]',
        reset_confirm_text: 'ARE YOU SURE YOU WANT TO\nPERMANENTLY RESET ALL PROGRESS?'
    },
    results: {
        iteration_complete: 'ITERATION ENDED',
        boss_defeated: 'BOSS DEFEATED',
        signal_lost: 'SIGNAL LOST',
        packet_sniffing_data: 'PASSIVE DATA EARNED: {0}',
        anomaly_detected: 'SYSTEM ANOMALY DETECTED',
        no_resources: 'NO RESOURCES',
        data_collected: 'DATA COLLECTED',
        insight_gained: '◐ INSIGHT gained: ',
        shards_found: '♦ SHARDS found: ',
        processors_salvaged: '■ PROCESSORS salvaged: ',
        diagnostic_report: '— DIAGNOSTIC REPORT —',
        no_damage_dealt: 'NO DAMAGE DEALT',
        insight_progress_title: 'INSIGHT',
        insight_progress_desc: 'Quantified experience. [b]INSIGHT[/b] unlocks upgrades that improve [color=cyan]DATA[/color] gathering.',
        cursor: 'CURSOR',
        tower: 'TOWER',
        lightning: 'LIGHTNING',
        shockwave: 'SHOCKWAVE',
        laser: 'LASER',
        artillery: 'ARTILLERY',
        collateral: 'COLLATERAL',
        system: 'SYSTEM'
    },
    loading_screen: {
        status: 'Loading... ({0})',
        slow: 'Slow loading detected',
        error: 'Load error, run game anyways?',
        run_anyways: 'RUN ANYWAYS'
    },
    tooltips: {
        max: 'MAX',
        active: 'ACTIVE',
        swap: 'CLICK TO SWAP'
    },
    hud: {
        data_title: '[color=cyan]DATA[/color]',
        data_desc: 'Common resource gained from enemies. Used for most upgrades.',
        insight_title: 'INSIGHT',
        insight_desc: 'A unit of compressed EXP. Improves [color=cyan]DATA[/color] gathering.',
        shard_title: 'AXIOM SHARD',
        shard_desc: 'A fragmented piece of the system\'s architecture. Unlocks powerful abilities.',
        processor_title: 'PROCESSOR',
        processor_desc: 'High-tier salvage. Used for advanced system modifications.',
        coin_title: '[color=#00FF00]COIN[/color]',
        coin_desc: 'A token that can influence the physical world. Provides high-tier upgrades.',
        health_title: 'HEALTH',
        health_desc: 'Your core\'s physical durability. If this reaches zero, the current iteration fails.',
        exp_title: 'EXPERIENCE',
        exp_desc: 'Progress toward your next INSIGHT. Gained passively over time while in combat.',
        exp: 'EXP ',
        exp_initial: 'EXP 0%',
        data_round: 'DATA'
    },
    popup: {
        insight_gained: '+LEVEL UP!',
        shard_acquired: '+1 SHARD ACQUIRED'
    },
    tower_stats: {
        title: 'AXIOM CORE',
        damage: 'DAMAGE: {0}',
        regen: 'REGEN: {0}/s',
        armor: 'ARMOR: {0}',
        range: 'RANGE: {0}',
        equipped: 'EQUIPPED SYSTEMS',
        none: 'NONE'
    }
};
